### ISSUE TITLE
Guake 3 doesn't start on Wayland

### ISSUE THREAD

**Issue by ppkt** [Guake/guake#1071]
It looks like Guake is no longer working on my box (I had no problems with Python 2.x version). I fetched latest version from git and after running `make run` I've got following error:
```
Traceback (most recent call last):
  File "guake/main.py", line 354, in <module>
    exec_main()
  File "guake/main.py", line 348, in exec_main
    if not main():
  File "guake/main.py", line 323, in main
    remote_object.show_hide()
  File "/home/ppkt/workspace/guake/guake/dbusiface.py", line 44, in show_hide
    self.guake.show_hide()
  File "/home/ppkt/workspace/guake/guake/guake_app.py", line 797, in show_hide
    self.show()
  File "/home/ppkt/workspace/guake/guake/guake_app.py", line 872, in show
    time = GdkX11.x11_get_server_time(self.window.get_window())
TypeError: argument window: Expected GdkX11.X11Window, but got __gi__.GdkWaylandWindow
Done
```
Solution from this patch solves my problem: https://launchpadlibrarian.net/309178299/wayland_fix.diff but I'm not sure if it's a proper way to fix this (I have no experience with Gnome at all)

**Comment by ppkt** [comment]
@Stibbons thank you very much - it's working now. However I found another exception (after Guake lose its focus):
```
DEBUG    Received window state event: <flags GDK_WINDOW_STATE_MAXIMIZED | GDK_WINDOW_STATE_FOCUSED | GDK_WINDOW_STATE_TILED | GDK_WINDOW_STATE_TOP_TILED | GDK_WINDOW_STATE_RIGHT_TILED | GDK_WINDOW_STATE_BOTTOM_TILED | GDK_WINDOW_STATE_LEFT_TILED of type Gdk.WindowState>
Traceback (most recent call last):
  File "/home/ppkt/workspace/guake/guake/guake_app.py", line 617, in on_window_losefocus
    self.losefocus_time = GdkX11.x11_get_server_time(self.window.get_window())
TypeError: argument window: Expected GdkX11.X11Window, but got __gi__.GdkWaylandWindow
```

**Comment by Stibbons** [comment]
Should be fixed in HEAD now can you try?

**Comment by ppkt** [comment]
Yes, now it's working like a charm - thanks :)

**Comment by cjustin88** [comment]
I'm still seeing a related (?) error when opening and closing Guake terminal. I have tried the latest master and tag 3.0.4.

```
connection.py:651:call_blocking:dbus.exceptions.DBusException: org.freedesktop.DBus.Python.NameError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/guake/utils.py", line 31, in get_server_time
    return GdkX11.x11_get_server_time(widget.get_window())
TypeError: argument window: Expected GdkX11.X11Window, but got __gi__.GdkWaylandWindow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/local/lib/python3.6/site-packages/guake/dbusiface.py", line 45, in show_hide
    self.guake.show_hide()
  File "/usr/local/lib/python3.6/site-packages/guake/guake_app.py", line 769, in show_hide
    self.set_terminal_focus()
  File "/usr/local/lib/python3.6/site-packages/guake/guake_app.py", line 889, in show
  File "/usr/local/lib/python3.6/site-packages/guake/utils.py", line 36, in get_server_time
    return get_local_timestamp()
NameError: name 'get_local_timestamp' is not defined


Traceback (most recent call last):
  File "/usr/local/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/local/lib/python3.6/site-packages/guake/main.py", line 356, in exec_main
    if not main():
  File "/usr/local/lib/python3.6/site-packages/guake/main.py", line 333, in main
    remote_object.show_hide()
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.NameError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/guake/utils.py", line 31, in get_server_time
    return GdkX11.x11_get_server_time(widget.get_window())
TypeError: argument window: Expected GdkX11.X11Window, but got __gi__.GdkWaylandWindow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/local/lib/python3.6/site-packages/guake/dbusiface.py", line 45, in show_hide
    self.guake.show_hide()
  File "/usr/local/lib/python3.6/site-packages/guake/guake_app.py", line 769, in show_hide
    self.set_terminal_focus()
  File "/usr/local/lib/python3.6/site-packages/guake/guake_app.py", line 889, in show
  File "/usr/local/lib/python3.6/site-packages/guake/utils.py", line 36, in get_server_time
    return get_local_timestamp()
NameError: name 'get_local_timestamp' is not defined


Local variables in innermost frame:
message: <dbus.lowlevel.MethodCallMessage path: /org/guake3/RemoteControl, iface: n/a, member: show_hide dest: :1.690>
get_args_opts: {'byte_arrays': False}
kwargs: {}
byte_arrays: False
timeout: -1.0
args: ()
signature: None
method: 'show_hide'
dbus_interface: None
object_path: '/org/guake3/RemoteControl'
bus_name: dbus.String(':1.690')
self: <dbus._dbus.SessionBus (session) at 0x7fd511428f68>
```
