### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'guake' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by Ozzyboshi** [Guake/guake#1077]
As the object of the issue states i get this error when i try to run guake3.0.1 just released, any hints?

~/github/guake-3.0.1$ make run
export GUAKE_DATA_DIR=/home/agarzi/github/guake-3.0.1/data ; pipenv run ./run-local.sh
execute Guake GTK3 for developer.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pbr/version.py", line 441, in _get_version_from_pkg_resources
    provider = pkg_resources.get_provider(requirement)
  File "/home/agarzi/.local/share/virtualenvs/guake-3.0.1-sEgByMQY/lib/python3.5/site-packages/pkg_resources/__init__.py", line 436, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/agarzi/.local/share/virtualenvs/guake-3.0.1-sEgByMQY/lib/python3.5/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/agarzi/.local/share/virtualenvs/guake-3.0.1-sEgByMQY/lib/python3.5/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'guake' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "guake/main.py", line 35, in <module>
    from guake.common import _
  File "/home/agarzi/github/guake-3.0.1/guake/__init__.py", line 23, in <module>
    __version__ = pbr.version.VersionInfo('guake').version_string()
  File "/usr/local/lib/python3.5/dist-packages/pbr/version.py", line 466, in version_string
    return self.semantic_version().brief_string()
  File "/usr/local/lib/python3.5/dist-packages/pbr/version.py", line 461, in semantic_version
    self._semantic = self._get_version_from_pkg_resources()
  File "/usr/local/lib/python3.5/dist-packages/pbr/version.py", line 448, in _get_version_from_pkg_resources
    result_string = packaging.get_version(self.package)
  File "/usr/local/lib/python3.5/dist-packages/pbr/packaging.py", line 755, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name guake was given, but was not able to be found.
Done

**Comment by Stibbons** [comment]
Did you checkout the code or used the .zip provided by github? This should not work, since the git history is mandatory to use PBR with. Can you can a git checkout?

**Comment by Ozzyboshi** [comment]
i tried to clone the github repo and time make all, the behaviour changes:

make all ends with this:
pipenv run autopep8 --in-place --recursive setup.py guake
pipenv run yapf --style .yapf --recursive -i guake
pipenv run python setup.py flake8
running flake8
pipenv run pylint --rcfile=.pylintrc --output-format=colorized guake
Using config file /home/agarzi/github/guake3/guake/.pylintrc
************* Module guake.notifier
guake/notifier.py:24: [E0611(no-name-in-module), ] No name 'Notify' in module 'gi.repository'
************* Module guake.guake_app
guake/guake_app.py:34: [E0611(no-name-in-module), ] No name 'Vte' in module 'gi.repository'
************* Module guake.prefs
guake/prefs.py:31: [E0611(no-name-in-module), ] No name 'Vte' in module 'gi.repository'
************* Module guake.terminal
guake/terminal.py:29: [E0611(no-name-in-module), ] No name 'Vte' in module 'gi.repository'
************* Module guake.gsettings
guake/gsettings.py:28: [E0611(no-name-in-module), ] No name 'Vte' in module 'gi.repository'

-----------------------------------
Your code has been rated at 9.91/10

Makefile:113: set di istruzioni per l'obiettivo "pylint" non riuscito
make: *** [pylint] Errore 2

make run with this

execute Guake GTK3 for developer.
Traceback (most recent call last):
  File "guake/main.py", line 35, in <module>
    from guake.common import _
  File "/home/agarzi/github/guake3/guake/guake/common.py", line 27, in <module>
    gi.require_version('Vte', '2.91')  # vte-0.38
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available
Done

it seems that vte is not installed
of course i previously run bootstrap-debian.sh and bootstrap-pip.sh
I am on debian 9

any hints?

**Comment by Stibbons** [comment]
I have this problem when I have `/usr/bin/python` pointing to python 3.6. On debian, it seems like pygtk3 works well only with python 3.5

**Comment by Ozzyboshi** [comment]
It seems i solved the problem installing gir1.2-vte-2.91 with 
sudo apt-get install gir1.2-vte-2.91

If this package is needed I would expect it to be listed into bootstrap-dev-debian.sh but i see the only one is gir1.2-keybinder-3.0

Now I have another problem, it's complaining about Notify 0.7 any suggestion?

make run
rm -f guake/data/gschemas.compiled
glib-compile-schemas --strict guake/data/
export GUAKE_DATA_DIR=/home/agarzi/github/guake3/guake/data ; pipenv run ./run-local.sh
execute Guake GTK3 for developer.
Traceback (most recent call last):
  File "guake/main.py", line 39, in <module>
    from guake.guake_app import Guake
  File "/home/agarzi/github/guake3/guake/guake/guake_app.py", line 48, in <module>
    from guake import notifier
  File "/home/agarzi/github/guake3/guake/guake/notifier.py", line 22, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
Done

**Comment by Ozzyboshi** [comment]
I installed gir1.2-notify-0.7 (sudo apt-get install gir1.2-notify-0.7), now it starts, would you accept a new pull request with this new 2 packages added into bootstrap-dev-debian.sh ?

**Comment by Stibbons** [comment]
thanks a lot :)

**Comment by kofiav** [comment]
Just want to say that @omidraha suggestion worked for me. 
` sudo apt-get install libkeybinder-3.0-0 gir1.2-keybinder`
