### ISSUE TITLE
2 issues - command options don't work, crash when disabling keybinding

### ISSUE THREAD

**Issue by luisnabais** [Guake/guake#1111]
**Description**
If I run guake -t, or guake --hide, or guake --show, for example, I always get:
```
INFO:guake.guake_logging:Logging configuration complete
DEBUG:guake.guake_logging:Debug mode enabled
INFO:guake.main:Guake is already running
```
If I try to disable Keybinding for Toggle Visibility, as soon as I press Backspace, Guake crashes instantly.

i'm using Arch Linux.
This only happens in today's update, yesterday's version was working perfectly.
I tried removing the home folder for guake, but the issues remain.

I'm using GNOME, fully updated.

**Additional info**
* package version(s)
Guake Terminal 3.0.2+6+ge9df754

Steps to reproduce:
1.
Run in console/command line, any of the commands:
```
$ guake -t
$ guake --show
$ guake --hide
```
2.
Go to Guake Preferences -> Keybindings -> Try to change keybinding for Toggle Visibility and press Backspace, to remove keybinding.

Thank you very much.
Best regards,
Luís Nabais

**Comment by Stibbons** [comment]
prefs panel is buggy indeed, and i already experienced you issue with "Guake is already running". DBus seems also to be not fully working

**Comment by presianbg** [comment]
Guake is not starting after upgrade from 0.8 to 3.0.2 on Arch Linux.

**Comment by Stibbons** [comment]
Which error?

**Comment by presianbg** [comment]
```
INFO:guake.guake_logging:Logging configuration complete
DEBUG:guake.guake_logging:Debug mode enabled
DEBUG:guake.main:DBus not running, starting it
INFO:guake.guake_logging:Logging configuration complete
DEBUG:guake.guake_app:set_final_window_rect
DEBUG:guake.guake_app:  height_percents = 83.54037267080744
DEBUG:guake.guake_app:  width_percents = 100.0
DEBUG:guake.guake_app:  halignment = 0
DEBUG:guake.guake_app:  valignment = 0
DEBUG:guake.guake_app:Current monitor geometry
DEBUG:guake.guake_app:  window_rect.x: 0
DEBUG:guake.guake_app:  window_rect.y: 0
DEBUG:guake.guake_app:  window_rect.height: 1080
DEBUG:guake.guake_app:  window_rect.width: 1920
DEBUG:guake.guake_app:is unity: False
DEBUG:guake.guake_app:Correcteed monitor size:
DEBUG:guake.guake_app:  total_width: 1920
DEBUG:guake.guake_app:  total_height: 1080
DEBUG:guake.guake_app:RESIZING MAIN WINDOW TO THE FOLLOWING VALUES:
DEBUG:guake.guake_app:  window_rect.x: 0
DEBUG:guake.guake_app:  window_rect.y: 0
DEBUG:guake.guake_app:  window_rect.height: 902
DEBUG:guake.guake_app:  window_rect.width: 1920
DEBUG:guake.guake_app:Updated window position: (root_x=0, root_y=0)
DEBUG:guake.guake_app:set_final_window_rect
DEBUG:guake.guake_app:  height_percents = 83.54037267080744
DEBUG:guake.guake_app:  width_percents = 100.0
DEBUG:guake.guake_app:  halignment = 0
DEBUG:guake.guake_app:  valignment = 0
DEBUG:guake.guake_app:Current monitor geometry
DEBUG:guake.guake_app:  window_rect.x: 0
DEBUG:guake.guake_app:  window_rect.y: 0
DEBUG:guake.guake_app:  window_rect.height: 1080
DEBUG:guake.guake_app:  window_rect.width: 1920
DEBUG:guake.guake_app:is unity: False
DEBUG:guake.guake_app:Correcteed monitor size:
DEBUG:guake.guake_app:  total_width: 1920
DEBUG:guake.guake_app:  total_height: 1080
DEBUG:guake.guake_app:RESIZING MAIN WINDOW TO THE FOLLOWING VALUES:
DEBUG:guake.guake_app:  window_rect.x: 0
DEBUG:guake.guake_app:  window_rect.y: 0
DEBUG:guake.guake_app:  window_rect.height: 902
DEBUG:guake.guake_app:  window_rect.width: 1920
DEBUG:guake.guake_app:Updated window position: (root_x=0, root_y=0)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 235, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 344, in exec_main
    if not main():
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 239, in main
    instance = Guake()
  File "/usr/lib/python3.6/site-packages/guake/guake_app.py", line 381, in __init__
    self.add_tab()
  File "/usr/lib/python3.6/site-packages/guake/guake_app.py", line 1736, in add_tab
    pid = self.spawn_sync_pid(directory, box.terminal)
  File "/usr/lib/python3.6/site-packages/guake/guake_app.py", line 1668, in spawn_sync_pid
    Vte.PtyFlags.DEFAULT, wd, argv, [], GLib.SpawnFlags.DO_NOT_REAP_CHILD, None, None, None
GLib.Error: g-exec-error-quark: Failed to execute child process “-” (No such file or directory) (8)

```

**Comment by Stibbons** [comment]
can you try a 

   make reset

to clean your settings?

**Comment by presianbg** [comment]
I'm not building it from source, just installing latest package. 
How to clear the settings in this case ?

**Comment by Stibbons** [comment]
```
dconf reset -f /apps/guake/
```

**Comment by presianbg** [comment]
Thanks!

**Comment by aichingm** [comment]
@presianbg could you try it with HEAD? Should be fixed.

**Comment by Stibbons** [comment]
I don't reproduce

**Comment by luisnabais** [comment]
Latest version (3.0.3) from yesterday has the issue solved. Thanks a lot.
