### ISSUE TITLE
Source code make error

### ISSUE THREAD

**Issue by narukamiko** [Guake/guake#1125]
Output below:
`Error opening directory “/usr/local/lib/python3.6/site-packages/guake/data/”: No such file or directory
make: *** [Makefile:43: install-system] Error 1
`
How can I solve it?

**Comment by aichingm** [comment]
what distro are you running?

**Comment by narukamiko** [comment]
@aichingm Linux version 4.14.13-1-ARCH (builduser@heftig-32336) (gcc version 7.2.1 20171224 (GCC))

**Comment by Stibbons** [comment]
Can you look where this command installs guake on your arch:
```
pipenv run python setup.py install
```

**Comment by aichingm** [comment]
Could you try   `make install-system PREFIX="usr/"`?

**Comment by narukamiko** [comment]
@aichingm 
`install -Dm644 "guake/data/guake.desktop" "usr//share/applications/guake.desktop"
install -Dm644 "guake/data/guake-prefs.desktop" "usr//share/applications/guake-prefs.desktop"
install -Dm644 "guake/data/pixmaps/guake.png" "usr//share/pixmaps/guake.png"
install -Dm644 "guake/data/org.guake.gschema.xml" "usr//share/glib-2.0/schemas/org.guake.gschema.xml"
glib-compile-schemas usr//share/glib-2.0/schemas/
for f in $(find po -iname "*.mo"); do \
        l="${f%%.*}"; \
        lb=$(basename $l); \
        install -Dm644 "$f" "usr//share/locale/$lb/LC_MESSAGES/guake.mo"; \
done;
# you probably want to execute this target with sudo:
# sudo make install
Installing from on your system is not recommended.
Please prefer you application package manager (apt, yum, ...)
Requirement already satisfied: pbr in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 13))
running install
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] ChangeLog complete (0.0s)
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.0s)
running build
running build_py
running egg_info
writing Guake.egg-info/PKG-INFO
writing dependency_links to Guake.egg-info/dependency_links.txt
writing entry points to Guake.egg-info/entry_points.txt
writing requirements to Guake.egg-info/requires.txt
writing top-level names to Guake.egg-info/top_level.txt
writing pbr to Guake.egg-info/pbr.json
[pbr] Processing SOURCES.txt
[pbr] In git context, generating filelist from git
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'Guake.egg-info/SOURCES.txt'
running install_lib
writing byte-compilation script '/tmp/tmpyv5p7efo.py'
/usr/bin/python3 /tmp/tmpyv5p7efo.py
removing /tmp/tmpyv5p7efo.py
running install_egg_info
removing '/usr/lib/python3.6/site-packages/Guake-3.0.3.dev18-py3.6.egg-info' (and everything under it)
Copying Guake.egg-info to /usr/lib/python3.6/site-packages/Guake-3.0.3.dev18-py3.6.egg-info
running install_scripts
Installing guake script to /usr/bin
Error opening directory “usr//lib/python3.6/site-packages/guake/data/”: No such file or directory
make: *** [Makefile:43: install-system] Error 1
`

It doesn't work.

**Comment by Stibbons** [comment]
Use absolute path:

make install-system PREFIX=/usr

Why not in /usr/local, i am use to not mess with the défaut packages.
For official package indeed it should be in /usr

**Comment by aichingm** [comment]
@Stibbons is right use /usr not usr/. 

on arch `@$(PYTHON_INTERPRETER) setup.py install --root "$(INSTALL_ROOT)" --optimize=1
` installs into /usr/lib and not into /usr/local/lib
so the PREFIX has to match this path.

**Comment by narukamiko** [comment]
@aichingm @Stibbons 
```
INFO:guake.guake_logging:Logging configuration complete
DEBUG:guake.guake_logging:Debug mode enabled
DEBUG:guake.main:DBus not running, starting it
INFO:guake.guake_logging:Logging configuration complete
DEBUG:guake.guake_app:set_final_window_rect
DEBUG:guake.guake_app:  height_percents = 94.80519480519477
DEBUG:guake.guake_app:  width_percents = 100.0
DEBUG:guake.guake_app:  halignment = 0
DEBUG:guake.guake_app:  valignment = 0
DEBUG:guake.guake_app:Current monitor geometry
DEBUG:guake.guake_app:  window_rect.x: 0
DEBUG:guake.guake_app:  window_rect.y: 0
DEBUG:guake.guake_app:  window_rect.height: 1080
DEBUG:guake.guake_app:  window_rect.width: 1920
DEBUG:guake.guake_app:is unity: False
DEBUG:guake.guake_app:Correcteed monitor size:
DEBUG:guake.guake_app:  total_width: 1920
DEBUG:guake.guake_app:  total_height: 1080
DEBUG:guake.guake_app:RESIZING MAIN WINDOW TO THE FOLLOWING VALUES:
DEBUG:guake.guake_app:  window_rect.x: 0
DEBUG:guake.guake_app:  window_rect.y: 0
DEBUG:guake.guake_app:  window_rect.height: 1023
DEBUG:guake.guake_app:  window_rect.width: 1920
DEBUG:guake.guake_app:Updated window position: (root_x=0, root_y=0)
DEBUG:guake.guake_app:set_final_window_rect
DEBUG:guake.guake_app:  height_percents = 94.80519480519477
DEBUG:guake.guake_app:  width_percents = 100.0
DEBUG:guake.guake_app:  halignment = 0
DEBUG:guake.guake_app:  valignment = 0
DEBUG:guake.guake_app:Current monitor geometry
DEBUG:guake.guake_app:  window_rect.x: 0
DEBUG:guake.guake_app:  window_rect.y: 0
DEBUG:guake.guake_app:  window_rect.height: 1080
DEBUG:guake.guake_app:  window_rect.width: 1920
DEBUG:guake.guake_app:is unity: False
DEBUG:guake.guake_app:Correcteed monitor size:
DEBUG:guake.guake_app:  total_width: 1920
DEBUG:guake.guake_app:  total_height: 1080
DEBUG:guake.guake_app:RESIZING MAIN WINDOW TO THE FOLLOWING VALUES:
DEBUG:guake.guake_app:  window_rect.x: 0
DEBUG:guake.guake_app:  window_rect.y: 0
DEBUG:guake.guake_app:  window_rect.height: 1023
DEBUG:guake.guake_app:  window_rect.width: 1920
DEBUG:guake.guake_app:Updated window position: (root_x=0, root_y=0)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 235, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 339, in exec_main
    if not main():
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 239, in main
    instance = Guake()
  File "/usr/lib/python3.6/site-packages/guake/guake_app.py", line 381, in __init__
    self.add_tab()
  File "/usr/lib/python3.6/site-packages/guake/guake_app.py", line 1736, in add_tab
    pid = self.spawn_sync_pid(directory, box.terminal)
  File "/usr/lib/python3.6/site-packages/guake/guake_app.py", line 1668, in spawn_sync_pid
    Vte.PtyFlags.DEFAULT, wd, argv, [], GLib.SpawnFlags.DO_NOT_REAP_CHILD, None, None, None
GLib.Error: g-exec-error-quark: Failed to execute child process “-” (No such file or directory) (8)
```
Yet, #1119 still exits.

**Comment by aichingm** [comment]
@narukamiko but you ware able to run make install successfully? So this issue can be closed?

**Comment by narukamiko** [comment]
@aichingm 
All right. Thanks.
