### ISSUE TITLE
Guake does not work

### ISSUE THREAD

**Issue by narukamiko** [Guake/guake#1151]
```
Logging configuration complete
Debug mode enabled
DBus not running, starting it
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 236, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/guake", line 11, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 340, in exec_main
    if not main():
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 240, in main
    instance = Guake()
  File "/usr/lib/python3.6/site-packages/guake/guake_app.py", line 157, in __init__
    SCHEMA_DIR, Gio.SettingsSchemaSource.get_default(), False
GLib.Error: g-file-error-quark: Failed to open file “/usr/lib/python3.6/site-packages/guake/data/gschemas.compiled”: open() failed: No such file or directory (4)

```
How can I solve it?

**Comment by Stibbons** [comment]
did you installed with `sudo make install` ?

**Comment by narukamiko** [comment]
@Stibbons Of course.

**Comment by Stibbons** [comment]
it should have installed it in /usr/local/bin/guake. Can you manually remove /usr/bin/guake, I don't know where it comes from?

**Comment by narukamiko** [comment]
Well, I remove `/usr/bin/guake` and reinstall it through `sudo make install-system PREFIX=/usr`. 
And it works but it still in `/usr/bin`

**Comment by Stibbons** [comment]
use `sudo make install`. Do not force in `/usr`
