### ISSUE TITLE
Guake now crashes due to dbus error

### ISSUE THREAD

**Issue by Ozzyboshi** [Guake/guake#1185]
I've just performed a git pull and i am now on commit db470cd924425044b289ad47deab2a2b77d35cd1

but now guake won't start, it crashes with the message, I saw some work has been down on the latest Guake release, maybe something related to this?

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "guake/main.py", line 241, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "guake/main.py", line 368, in <module>
    exec_main()
  File "guake/main.py", line 356, in exec_main
    if not main():
  File "guake/main.py", line 256, in main
    instance = Guake()
  File "/home/agarzi/github/guake3/guake/guake/guake_app.py", line 154, in __init__
    super(Guake, self).__init__(gladefile('guake.glade'))
  File "/home/agarzi/github/guake3/guake/guake/common.py", line 61, in gladefile
    raise IOError('No such file or directory: %s' % f)
OSError: No such file or directory: /home/agarzi/github/guake3/guake/data/guake.glade

**Comment by gsemet** [comment]
did you followed the instructions in README? You still need to install the schema even for development mode

**Comment by Ozzyboshi** [comment]
solved thx

**Comment by romange** [comment]
@gsemet  when I perform "pip3 install guake" on clean Ubuntu 18.04 installation, guake crashes for me with this error.

**Comment by gsemet** [comment]
you may need to manually install the schema when using pip install. pip does not do that by default.

**Comment by romange** [comment]
@gsemet  what do you mean by schema? 
gsettings-desktop-schemas is installed on my system.

**Comment by tli47** [comment]
I met the same crashed issue when I ran "pip install guake" on fedora 31.
If I need to install guake schema as @gsemet mentioned above, how need I need to do?
Or any other solution?
