### ISSUE TITLE
Void Linux compatibility

### ISSUE THREAD

**Issue by Jakecheslekov** [Guake/guake#1187]
Before opening a new issue, please read the following:

- for **feature requests**, please use [FeatHub](https://feathub.com/Guake/guake). This allow us to
  spot directly which are the most requested features.
- before opening **a new bug**, please search for a similar one in the GitHub issue.
- to **report a bug**, please give the following information:

  - **Guake Version**: see in about box.
  - The bug may have been already reported and fixed on the main development branch `master`. If you
    are confortable with building Guake from source, known if the bug is still on HEAD is a very
    valuable information
  - Please describe **your system** (Linux distribution and GNOME version).

Hey guys. I've tried to compile Guake on void linux, but I'm getting a funny error, like I missed a dependency or something.

/usr/bin/python2: No module named guake

I can't figure out what I might be missing.... Is there by chance a guake-gtk2 in pip?

**Comment by Jakecheslekov** [comment]
> guake
Logging configuration complete
DBus not running, starting it
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in 
activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in 
get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, 
in call_blocking
    message, timeout)
dbus.exceptions.DBusException: 
org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 
'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 241, in 
main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in 
get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in 
__init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in 
activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in 
start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, 
in call_blocking
    message, timeout)
dbus.exceptions.DBusException: 
org.freedesktop.DBus.Error.ServiceUnknown: The name 
org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 356, in 
exec_main
    if not main():
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 256, in 
main
    instance = Guake()
  File "/usr/lib/python3.6/site-packages/guake/guake_app.py", line 159, 
in __init__
    SCHEMA_DIR, Gio.SettingsSchemaSource.get_default(), False
GLib.Error: g-file-error-quark: Failed to open file 
“/usr/lib/python3.6/site-packages/guake/data/gschemas.compiled”: open() 
failed: No such file or directory (4)

>

**Comment by Jakecheslekov** [comment]
When I build it with python setup.py build + install I get:

Logging configuration complete
DBus not running, starting it
Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python2.7/site-packages/guake/main.py", line 356, in exec_main
    if not main():
  File "/usr/lib/python2.7/site-packages/guake/main.py", line 255, in main
    from guake.guake_app import Guake
  File "/usr/lib/python2.7/site-packages/guake/guake_app.py", line 30, in <module>
    from urllib.parse import quote_plus
ImportError: No module named parse

**Comment by gsemet** [comment]
Guake 3 is now python 3 only. You cannot use it for Python 2 which is near its end of life

**Comment by Jakecheslekov** [comment]
These are the errors I get with python3... ./run-local.sh will open the terminal though.

DBus not running, starting it
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in 
activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in 
get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, 
in call_blocking
    message, timeout)
dbus.exceptions.DBusException: 
org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 
'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 241, in 
main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in 
get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in 
__init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in 
activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in 
start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, 
in call_blocking
    message, timeout)
dbus.exceptions.DBusException: 
org.freedesktop.DBus.Error.ServiceUnknown: The name 
org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 356, in 
exec_main
    if not main():
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 256, in 
main
    instance = Guake()
  File "/usr/lib/python3.6/site-packages/guake/guake_app.py", line 159, 
in __init__
    SCHEMA_DIR, Gio.SettingsSchemaSource.get_default(), False
GLib.Error: g-file-error-quark: Failed to open file 
“/usr/lib/python3.6/site-packages/guake/data/gschemas.compiled”: open() 
failed: No such file or directory (4)

**Comment by gsemet** [comment]
there may be an issue with dist-packages / site-packages... we may have tainted too much with debian/ubuntu

**Comment by Jakecheslekov** [comment]
Yeah, site-packages is where I see all of these errors.

**Comment by Jakecheslekov** [comment]
Oh my lord, I've got it working! I cannot believe it!
I had to install pycode, flake/pyflake, mccabe, and a few other python modules, now it actually works! Yay!

**Comment by gsemet** [comment]
Make && make install ?

**Comment by Jakecheslekov** [comment]
Yeah, Guake 3.0 & 0.8.13. I had to do a lot of screwing around but I got it.

**Comment by Jakecheslekov** [comment]
I forgot to mention I had to use some commands I stole from a arch linux PKGBUILD:

PYTHON=$(which python2) ./autogen.sh --prefix=/usr --sysconfdir=/usr/share --disable-static

make GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 DESTDIR="$pkgdir" install

**Comment by gsemet** [comment]
where does the autogen.sh comes from? It is only for 0.8

If you find a clean way to install Guake 3 on void linux, I'll be very thankful if you can put a note in the README

**Comment by Jakecheslekov** [comment]
I managed to install guake 3.0 the other day I think, I am currently strapped for time but in a few days I will come back & try it. Yes sorry forgot to mention that was just for Guake GTK2, I use LXDE & this computer I work on is a tad bit old so I prefer to stay with the GTK2 stuff.
