### ISSUE TITLE
Exception when opening Guake in Wayland

### ISSUE THREAD

**Issue by cjustin88** [Guake/guake#1215]
I think this is related to https://github.com/Guake/guake/issues/1071. I have tried the latest master and tag 3.0.4.
```
connection.py:651:call_blocking:dbus.exceptions.DBusException: org.freedesktop.DBus.Python.NameError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/guake/utils.py", line 31, in get_server_time
    return GdkX11.x11_get_server_time(widget.get_window())
TypeError: argument window: Expected GdkX11.X11Window, but got __gi__.GdkWaylandWindow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/local/lib/python3.6/site-packages/guake/dbusiface.py", line 45, in show_hide
    self.guake.show_hide()
  File "/usr/local/lib/python3.6/site-packages/guake/guake_app.py", line 769, in show_hide
    self.set_terminal_focus()
  File "/usr/local/lib/python3.6/site-packages/guake/guake_app.py", line 889, in show
  File "/usr/local/lib/python3.6/site-packages/guake/utils.py", line 36, in get_server_time
    return get_local_timestamp()
NameError: name 'get_local_timestamp' is not defined


Traceback (most recent call last):
  File "/usr/local/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/local/lib/python3.6/site-packages/guake/main.py", line 356, in exec_main
    if not main():
  File "/usr/local/lib/python3.6/site-packages/guake/main.py", line 333, in main
    remote_object.show_hide()
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.NameError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/guake/utils.py", line 31, in get_server_time
    return GdkX11.x11_get_server_time(widget.get_window())
TypeError: argument window: Expected GdkX11.X11Window, but got __gi__.GdkWaylandWindow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/local/lib/python3.6/site-packages/guake/dbusiface.py", line 45, in show_hide
    self.guake.show_hide()
  File "/usr/local/lib/python3.6/site-packages/guake/guake_app.py", line 769, in show_hide
    self.set_terminal_focus()
  File "/usr/local/lib/python3.6/site-packages/guake/guake_app.py", line 889, in show
  File "/usr/local/lib/python3.6/site-packages/guake/utils.py", line 36, in get_server_time
    return get_local_timestamp()
NameError: name 'get_local_timestamp' is not defined


Local variables in innermost frame:
message: <dbus.lowlevel.MethodCallMessage path: /org/guake3/RemoteControl, iface: n/a, member: show_hide dest: :1.690>
get_args_opts: {'byte_arrays': False}
kwargs: {}
byte_arrays: False
timeout: -1.0
args: ()
signature: None
method: 'show_hide'
dbus_interface: None
object_path: '/org/guake3/RemoteControl'
bus_name: dbus.String(':1.690')
self: <dbus._dbus.SessionBus (session) at 0x7fd511428f68>
```

**Comment by cjustin88** [comment]
Thanks, I confirm that https://github.com/Guake/guake/pull/1216 fixes it.
