### ISSUE TITLE
Guake -e issue

### ISSUE THREAD

**Issue by Dn4g** [Guake/guake#1222]
When I used '-e' option, at guake, have this fault:

```
~ $ guake -e 1
Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 356, in exec_main
    if not main():
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 297, in main
    remote_object.execute_command(options.command)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.6/site-packages/guake/dbusiface.py", line 103, in execute_command
    self.guake.execute_command(command)
  File "/usr/lib/python3.6/site-packages/guake/guake_app.py", line 549, in execute_command
    terminal.feed_child(command, len(command))
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)

```
~ $ guake -v
Guake Terminal 3.0.5

~ $ python -V
Python 3.6.4

Have installed the latest Arch linux with KDE Plasma.

$  plasmashell --version
plasmashell 5.12.4

Try to reinstall guake via pacman and pip, but it did not help.

What should I check?

**Comment by gsemet** [comment]
that's weird, my version of vte (vte-2.91) requires these 3 arguments (self, command, len(command))

**Comment by gsemet** [comment]
Duplicate of #1243. I cannot test, I would be glad if someone finds out the right call to feed_child
