### ISSUE TITLE
Vte.Terminal.set_allow_hyperlink() takes exactly 2 arguments

### ISSUE THREAD

**Issue by jtojnar** [Guake/guake#1264]
Running Guake 3.1.0 on NixOS fails with the following error:

```
Traceback (most recent call last):
  File "/nix/store/x5624cn4xi5bndfdpkzpn7m2g00dzs58-python3.6-dbus-python-1.2.4/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/nix/store/x5624cn4xi5bndfdpkzpn7m2g00dzs58-python3.6-dbus-python-1.2.4/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/nix/store/x5624cn4xi5bndfdpkzpn7m2g00dzs58-python3.6-dbus-python-1.2.4/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/h1iv59rph40wya4lnvkgvqaf0fx1a21q-guake-3.1.0/lib/python3.6/site-packages/guake/main.py", line 256, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/nix/store/x5624cn4xi5bndfdpkzpn7m2g00dzs58-python3.6-dbus-python-1.2.4/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/nix/store/x5624cn4xi5bndfdpkzpn7m2g00dzs58-python3.6-dbus-python-1.2.4/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/nix/store/x5624cn4xi5bndfdpkzpn7m2g00dzs58-python3.6-dbus-python-1.2.4/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/nix/store/x5624cn4xi5bndfdpkzpn7m2g00dzs58-python3.6-dbus-python-1.2.4/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/nix/store/x5624cn4xi5bndfdpkzpn7m2g00dzs58-python3.6-dbus-python-1.2.4/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/h1iv59rph40wya4lnvkgvqaf0fx1a21q-guake-3.1.0/bin/..guake-wrapped-wrapped", line 11, in <module>
    sys.exit(exec_main())
  File "/nix/store/h1iv59rph40wya4lnvkgvqaf0fx1a21q-guake-3.1.0/lib/python3.6/site-packages/guake/main.py", line 371, in exec_main
    if not main():
  File "/nix/store/h1iv59rph40wya4lnvkgvqaf0fx1a21q-guake-3.1.0/lib/python3.6/site-packages/guake/main.py", line 271, in main
    instance = Guake()
  File "/nix/store/h1iv59rph40wya4lnvkgvqaf0fx1a21q-guake-3.1.0/lib/python3.6/site-packages/guake/guake_app.py", line 381, in __init__
    self.add_tab()
  File "/nix/store/h1iv59rph40wya4lnvkgvqaf0fx1a21q-guake-3.1.0/lib/python3.6/site-packages/guake/guake_app.py", line 1760, in add_tab
    box = GuakeTerminalBox(self.settings)
  File "/nix/store/h1iv59rph40wya4lnvkgvqaf0fx1a21q-guake-3.1.0/lib/python3.6/site-packages/guake/terminal.py", line 480, in __init__
    self.terminal = GuakeTerminal(settings)
  File "/nix/store/h1iv59rph40wya4lnvkgvqaf0fx1a21q-guake-3.1.0/lib/python3.6/site-packages/guake/terminal.py", line 102, in __init__
    self.configure_terminal()
  File "/nix/store/h1iv59rph40wya4lnvkgvqaf0fx1a21q-guake-3.1.0/lib/python3.6/site-packages/guake/terminal.py", line 156, in configure_terminal
    self.set_allow_hyperlink()
TypeError: Vte.Terminal.set_allow_hyperlink() takes exactly 2 arguments (1 given)
```

We have VTE 0.52.0.

**Comment by jtojnar** [comment]
Same thing with 0.52.1.

**Comment by gsemet** [comment]
ok I have fixed the call on HEAD. However, I do not see how I can retreive the url from VTE ? Hard for me to test it, I don't have recent version of vte

**Comment by egmontkob** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/guake/terminal.py", line 290, in button_press
    self._on_ctrl_click_matcher((s, None))
  File "/usr/local/lib/python3.6/dist-packages/guake/terminal.py", line 315, in _on_ctrl_click_matcher
    if not found_matcher:
UnboundLocalError: local variable 'found_matcher' referenced before assignment
```

You're not saying you're developing blindly without being able to test, are you? :P Get a new VTE please.

**Comment by gsemet** [comment]
Hard to do, because I need to keep as close as Ubuntu as possible. But I use VM, if you know a distrib easy to install in Parallels with latest VTE, I’ll install it !

**Comment by jtojnar** [comment]
[Fedora Rawhide](https://fedoraproject.org/wiki/Releases/Rawhide) will probably have the latest GNOME packages. Alternately, you can install [Nix](https://nixos.org/nix/) package manager and run `nix-shell channel:nixpkgs-unstable -A guake` to open a shell with the necessary dependencies installed.

**Comment by gsemet** [comment]
no iso?

**Comment by egmontkob** [comment]
- Ubuntu Bionic will be released next week, meaning its beta is pretty solid and final. It ships vte-0.52.1.
- You can always install VTE at a nonstandard location, and point Guake to that (with e.g. LD_PRELOAD or LD_LIBRARY_PATH, although I'm not sure if there's something else to do for python/gir, e.g. for the build step).
- You can install a new VTE at the same location as your distro does, overriding its files. Then at any time you can uninstall it followed by reinstalling the distro's packages.
