### ISSUE TITLE
Ubuntu 18.04: FileNotFoundError: [Errno 2] No such file or directory: '/proc/4106/cwd'

### ISSUE THREAD

**Issue by beastie77** [Guake/guake#1312]
Hello,

Guake crashes on the new Ubuntu 18.04 (Bionic) after closing a term.
Here is some info:

OS: Ubuntu 18.04 x86_64
Guake version: 3.0.5-1
Python version: 3.6.5
Gnome version: 3.28.1-1

Here is the error message:
`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 1287, in accel_add
    self.add_tab()
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 1752, in add_tab
    pid = self.spawn_sync_pid(directory, box.terminal)
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 1667, in spawn_sync_pid
    wd = self.get_current_dir()
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 1643, in get_current_dir
    return active_terminal.get_current_directory()
  File "/usr/lib/python3/dist-packages/guake/terminal.py", line 186, in get_current_directory
    cwd = os.readlink("/proc/{}/cwd".format(self.pid))
FileNotFoundError: [Errno 2] No such file or directory: '/proc/4106/cwd'
`

To reproduce:

1) Open a Guake term as normal user
2) Type the "exit" command. Guake hangs now.
3) Press the shortcut: CTRL + SHIFT + T. Guake crashes and the previous error message is send to Ubuntu.

When looking in /proc there is indeed no /proc/4106 dir.

**Comment by gsemet** [comment]
Should be fixed on HEAD. Can you try to compile from source ?
