### ISSUE TITLE
sudo make install fails for 3.2.1 on fresh Ubuntu 18.04 install 

### ISSUE THREAD

**Issue by seantcanavan** [Guake/guake#1314]
Ubuntu 18.04 LTS
GNOME 3.28.1

Steps to reproduce:

1. Download https://github.com/Guake/guake/archive/3.2.1.zip to ~/Downloads
2. `unzip guake-3.2.1.zip`
3. `cd guake-3.2.1`
4. `./scripts/bootstrap-dev-debian.sh`
5. `make`
6. `sudo make install`
```

Fri Apr 27 03:18 PM guake-3.2.1: make
generating desktop files
cp -f guake/paths.py.in guake/paths.py
# Generic
# Dev environment:
sed -i -e 's|{{ LOCALE_DIR }}|/usr/local/share/locale|g' guake/paths.py
sed -i -e 's|{{ IMAGE_DIR }}|/home/username/Downloads/guake-3.2.1/data/pixmaps|g' guake/paths.py
sed -i -e 's|{{ GUAKE_THEME_DIR }}|/home/username/Downloads/guake-3.2.1/data/themes|g' guake/paths.py
sed -i -e 's|{{ GLADE_DIR }}|/home/username/Downloads/guake-3.2.1/data|g' guake/paths.py
sed -i -e 's|{{ SCHEMA_DIR }}|/home/username/Downloads/guake-3.2.1/data|g' guake/paths.py
generating po/tr.po
generating po/nb.po
generating po/ko.po
generating po/it.po
generating po/fa.po
generating po/hr.po
generating po/el.po
generating po/fr.po
generating po/pa.po
generating po/ru.po
generating po/pl.po
generating po/de.po
generating po/hu.po
generating po/pt_BR.po
generating po/uk.po
generating po/gl.po
generating po/id.po
generating po/sv.po
generating po/zh_CN.po
generating po/es.po
generating po/nl.po
generating po/ja.po
generating po/cs.po
generating po/ca.po
rm -f /home/username/Downloads/guake-3.2.1/data/gschemas.compiled
glib-compile-schemas --strict /home/username/Downloads/guake-3.2.1/data
# 'make' target, so users can install guake without need to install the 'dev' dependencies
Fri Apr 27 03:18 PM guake-3.2.1: sudo make install
install -Dm644 "/home/username/Downloads/guake-3.2.1/data/guake.desktop" "//usr/local/share/applications/guake.desktop"
install -Dm644 "/home/username/Downloads/guake-3.2.1/data/guake-prefs.desktop" "//usr/local/share/applications/guake-prefs.desktop"
mkdir -p //usr/local/share/guake/pixmaps
install -Dm644 /home/username/Downloads/guake-3.2.1/data/pixmaps/*.png "//usr/local/share/guake/pixmaps/"
install -Dm644 /home/username/Downloads/guake-3.2.1/data/pixmaps/*.svg "//usr/local/share/guake/pixmaps/"
install -Dm644 /home/username/Downloads/guake-3.2.1/data/pixmaps/guake.png "//usr/local/share/pixmaps/guake.png"
mkdir -p //usr/local/share/guake
mkdir -p //usr/local/share/guake
install -Dm644  /home/username/Downloads/guake-3.2.1/data/*.glade "//usr/local/share/guake"
mkdir -p //usr/local/share/guake
install -Dm644 "/home/username/Downloads/guake-3.2.1/data/autostart-guake.desktop" "//usr/local/share/guake"
mkdir -p //usr/local/share/glib-2.0/schemas
install -Dm644 "/home/username/Downloads/guake-3.2.1/data/org.guake.gschema.xml" "//usr/local/share/glib-2.0/schemas/"
if [ 1 = 1 ]; then glib-compile-schemas //usr/local/share/glib-2.0/schemas; fi
for f in $(find po -iname "*.mo"); do \
	l="${f%%.*}"; \
	lb=$(basename $l); \
	install -Dm644 "$f" "//usr/local/share/locale/$lb/LC_MESSAGES/guake.mo"; \
done;
# you probably want to execute this target with sudo:
# sudo make install
Installing from on your system is not recommended.
Please prefer you application package manager (apt, yum, ...)
The directory '/home/username/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/username/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Ignoring typing: markers 'python_version < "3.5"' don't match your environment
Requirement already satisfied: pbr in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 13))
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/local/lib/python3.6/dist-packages/pbr/util.py", line 258, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/local/lib/python3.6/dist-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/local/lib/python3.6/dist-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/local/lib/python3.6/dist-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/local/lib/python3.6/dist-packages/pbr/packaging.py", line 816, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name Guake was given, but was not able to be found.
error in setup command: Error parsing /home/username/Downloads/guake-3.2.1/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name Guake was given, but was not able to be found.
Makefile:73: recipe for target 'install-guake' failed
make: *** [install-guake] Error 1
```

**Comment by gsemet** [comment]
You need to use the git tree not the source tar all. They will not work with pbr. You need to fetch the sources with git clone.
