### ISSUE TITLE
Guake fails to start due to missing service

### ISSUE THREAD

**Issue by hedgehog1029** [Guake/guake#1317]
**Guake version: 3.2.1**
**Distro: Arch Linux**

Long traceback:
```
Guake not running, starting it
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 270, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 385, in exec_main
    if not main():
  File "/usr/lib/python3.6/site-packages/guake/main.py", line 285, in main
    instance = Guake()
  File "/usr/lib/python3.6/site-packages/guake/guake_app.py", line 168, in __init__
    log.info('Guake Terminal %s', guake_version())
  File "/usr/lib/python3.6/site-packages/guake/__init__.py", line 25, in guake_version
    return pbr.version.VersionInfo('guake').version_string()
  File "/usr/lib/python3.6/site-packages/pbr/version.py", line 467, in version_string
    return self.semantic_version().brief_string()
  File "/usr/lib/python3.6/site-packages/pbr/version.py", line 462, in semantic_version
    self._semantic = self._get_version_from_pkg_resources()
  File "/usr/lib/python3.6/site-packages/pbr/version.py", line 439, in _get_version_from_pkg_resources
    import pkg_resources
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 73, in <module>
    from pkg_resources.extern import appdirs
  File "/usr/lib/python3.6/site-packages/pkg_resources/extern/__init__.py", line 61, in load_module
    "distribution.".format(**locals())
ImportError: The 'appdirs' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

I seem to remember getting a similar ServiceUnknown error before, and fixing it, but I don't remember how.

**Comment by gsemet** [comment]
do you know if "The 'appdirs' package is required" means you need to pacman a package named "appdirs"?

**Comment by hedgehog1029** [comment]
```
~ ➥ pacman -Ss appdirs
extra/python-appdirs 1.4.3-1 [installed]
    A small Python module for determining appropriate platform-specific dirs, e.g.
    a "user data dir".
```

**Comment by gsemet** [comment]
seems to be an extra requirements for arch linux. Can you update scripts/bootstrap-dev?

**Comment by gsemet** [comment]
forget the dbus error, they are side effect of the error at the bottom

**Comment by hedgehog1029** [comment]
ok looks like I just have a fucked setuptools install
might just nuke my entire python install and try again, I think pip and pacman are fighting

**Comment by hedgehog1029** [comment]
okay I nuked guake with `pacman -Rsc guake` and nuked pip, which I think was self-installed, and guake works again after reinstallation.
thanks for your help, sorry to bother you :ok_hand:

**Comment by aichingm** [comment]
>  I think pip and pacman are fighting
Yes they do, a lot of pip packages are also available via pacman (python-*). I try to use "pacman"-packages (also from the aur) when ever possible and only use pip when everything else fails.

**Comment by gsemet** [comment]
always use pip through `pip install --user`to avoid conflict.
