### ISSUE TITLE
Schema installation failing: "schema id guake already specified"

### ISSUE THREAD

**Issue by coljac** [Guake/guake#1324]
Guake version: 3.2.1, current commit (43971f1):

When I `make install` I see the following on the console:

```
//usr/local/share/glib-2.0/schemas/org.guake.gschema.xml:4:1  Error on line 4 char 1: <schema id='guake'> already specified.  This entire file has been ignored.
```
If I `make install` (fails for 3.2.1 for another reason, but succeeds on master), then running Guake results in:

```Guake not running, starting it
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/guake/main.py", line 270, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/local/lib/python3.5/dist-packages/guake/main.py", line 385, in exec_main
    if not main():
  File "/usr/local/lib/python3.5/dist-packages/guake/main.py", line 285, in main
    instance = Guake()
  File "/usr/local/lib/python3.5/dist-packages/guake/guake_app.py", line 165, in __init__
    self.settings = Settings(schema_source)
  File "/usr/local/lib/python3.5/dist-packages/guake/settings.py", line 55, in __init__
    None
TypeError: Argument 0 does not allow None as a value
```

Which I assume is a consequence of the former.

**Comment by gsemet** [comment]
do you have any other guake schema in /usr/local/share/glib-2.0/schemas/?
can you try `make uninstall-old-schemas`to see if it clean this old schema?
