### ISSUE TITLE
Cannot start guake

### ISSUE THREAD

**Issue by narukamiko** [Guake/guake#1349]
I got this message when I started guake
```
Guake not running, starting it
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asuka/.local/lib/python3.6/site-packages/guake/main.py", line 273, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/home/asuka/.local/lib/python3.6/site-packages/guake/main.py", line 388, in exec_main
    if not main():
  File "/home/asuka/.local/lib/python3.6/site-packages/guake/main.py", line 287, in main
    from guake.guake_app import Guake
  File "/home/asuka/.local/lib/python3.6/site-packages/guake/guake_app.py", line 55, in <module>
    from guake.about import AboutDialog
  File "/home/asuka/.local/lib/python3.6/site-packages/guake/about.py", line 28, in <module>
    from guake.common import gladefile
  File "/home/asuka/.local/lib/python3.6/site-packages/guake/common.py", line 30, in <module>
    from guake.paths import GLADE_DIR
ModuleNotFoundError: No module named 'guake.paths'
```
My system info: Linux version 4.17.2-1-ARCH (builduser@heftig-9574) (gcc version 8.1.1 20180531 (GCC)) 
Besides, I re-installed guake through Arch repo and git repo. The issue still existed.

**Comment by gsemet** [comment]
look like a bad install. Remove all under /home/asuka/.local/lib/python3.6/site-packages/guake.

Can you try the latest `pip install --user guake`? does it work?

**Comment by narukamiko** [comment]
@gsemet Thanks for your suggestions. It works.

**Comment by russmack** [comment]
I have this issue.  I tried the above suggestion.  It opened once.  Subsequent attempts at opening and reinstalling result in the above error.  For the time being reverting to apt install (v3.0.5).

**Comment by joskfg** [comment]
I have the same issue with a fresh install (after uninstalling old guake)

**Comment by aichingm** [comment]
Since this seams to be resolved by https://github.com/Guake/guake/issues/1349#issuecomment-400125814 and/or https://github.com/Guake/guake/issues/1328#issuecomment-397480686 I'm going to close this issue.
