### ISSUE TITLE
[Docs-Contributing2Guake] 'make run' fail

### ISSUE THREAD

**Issue by pleycpl** [Guake/guake#1353]
OS: Antergos Linux x86_64 4.17.3-1-ARCH
GNOME Shell: 3.28.2
Gtk3: 3.22.30
Python: 3.6.5
GCC: 8.1.0
Vte-common: 0.52.2
Vte3: 0.52.2

https://guake.readthedocs.io/en/stable/contributing/dev_env.html

```bash
$ sudo bash ./scripts/bootstrap-dev-arch.sh
...
$ make dev
./scripts/bootstrap-dev-pip.sh
Freeze version of pip to ensure build reproductibility
Requirement already up-to-date: pip>=10 in /usr/lib/python3.6/site-packages (10.0.1)
Requirement already up-to-date: pipenv>=11.10 in /home/pleycpl/.local/lib/python3.6/site-packages (2018.7.1)
Requirement already up-to-date: setuptools!=36.6.0 in /usr/lib/python3.6/site-packages (39.2.0)
Requirement not upgraded as not directly required: virtualenv in /usr/lib/python3.6/site-packages (from pipenv>=11.10) (16.0.0)
Requirement not upgraded as not directly required: certifi in /usr/lib/python3.6/site-packages (from pipenv>=11.10) (2018.4.16)
Requirement not upgraded as not directly required: virtualenv-clone>=0.2.5 in /usr/lib/python3.6/site-packages (from pipenv>=11.10) (0.3.0)
localstack 0.8.6.2 has requirement flask==0.10.1, but you'll have flask 1.0.2 which is incompatible.
localstack 0.8.6.2 has requirement psutil==5.4.3, but you'll have psutil 5.4.6 which is incompatible.
localstack 0.8.6.2 has requirement requests==2.18.4, but you'll have requests 2.19.1 which is incompatible.
elasticsearch 6.2.0 has requirement urllib3<1.23,>=1.21.1, but you'll have urllib3 1.23 which is incompatible.
Please ensure your local bin directory is in your path
Linux: export PATH=/home/pleycpl/.local/bin/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/pleycpl/.gem/ruby/2.5.0/bin
pipenv install --dev --python python3
Creating a virtualenv for this project...
Pipfile: /home/pleycpl/Documents/github/Guake/guake/Pipfile
Using /usr/bin/python3 (3.6.5) to create virtualenv...
⠋Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/pleycpl/.local/share/virtualenvs/guake-0duseqCa/bin/python3
Also creating executable in /home/pleycpl/.local/share/virtualenvs/guake-0duseqCa/bin/python
Installing setuptools, pip, wheel...done.
Setting project for guake-0duseqCa to /home/pleycpl/Documents/github/Guake/guake

Virtualenv location: /home/pleycpl/.local/share/virtualenvs/guake-0duseqCa
Installing dependencies from Pipfile.lock (76bfbb)...
Ignoring typing: markers 'python_version < "3.5"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 55/55 — 00:00:30
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
pipenv run pipenv_to_requirements
generated: requirements.txt
generated: requirements-dev.txt
# use that to configure a symbolic link to the virtualenv in .venv
rm -rf .venv
ln -s $(pipenv --venv) .venv
rm -f .git/hooks/post-commit
cp -fv git-hooks/* .git/hooks/
'git-hooks/post-commit' -> '.git/hooks/post-commit'
generating desktop files
Generating path.py...
generating po/id.po
generating po/fr.po
generating po/ja.po
generating po/hr.po
generating po/fa.po
generating po/ca.po
generating po/zh_CN.po
generating po/pt_BR.po
generating po/it.po
generating po/nl.po
generating po/nb.po
generating po/sv.po
generating po/ru.po
generating po/tr.po
generating po/hu.po
generating po/ko.po
generating po/el.po
generating po/pl.po
generating po/pa.po
generating po/cs.po
generating po/uk.po
generating po/de.po
generating po/es.po
generating po/gl.po
rm -f /home/pleycpl/Documents/github/Guake/guake/data/gschemas.compiled
glib-compile-schemas --strict /home/pleycpl/Documents/github/Guake/guake/data
$$$$$$$$$$$$$$$$$$$$$$$$$$$ sudo make install-schemas
install -Dm644 "/home/pleycpl/Documents/github/Guake/guake/data/guake.desktop" "//usr/local/share/applications/guake.desktop"
install -Dm644 "/home/pleycpl/Documents/github/Guake/guake/data/guake-prefs.desktop" "//usr/local/share/applications/guake-prefs.desktop"
mkdir -p //usr/local/share/guake/pixmaps
install -Dm644 /home/pleycpl/Documents/github/Guake/guake/data/pixmaps/*.png "//usr/local/share/guake/pixmaps/"
install -Dm644 /home/pleycpl/Documents/github/Guake/guake/data/pixmaps/*.svg "//usr/local/share/guake/pixmaps/"
install -Dm644 /home/pleycpl/Documents/github/Guake/guake/data/pixmaps/guake.png "//usr/local/share/pixmaps/guake.png"
mkdir -p //usr/local/share/guake
mkdir -p //usr/local/share/guake
install -Dm644  /home/pleycpl/Documents/github/Guake/guake/data/*.glade "//usr/local/share/guake"
mkdir -p //usr/local/share/guake
install -Dm644 "/home/pleycpl/Documents/github/Guake/guake/data/autostart-guake.desktop" "//usr/local/share/guake"
mkdir -p //usr/local/share/glib-2.0/schemas
install -Dm644 "/home/pleycpl/Documents/github/Guake/guake/data/org.guake.gschema.xml" "//usr/local/share/glib-2.0/schemas/"
$$$$$$$$$$$$$$$$$$$$$$$$$$$ make run
rm -f /home/pleycpl/Documents/github/Guake/guake/data/gschemas.compiled
glib-compile-schemas --strict /home/pleycpl/Documents/github/Guake/guake/data
pipenv run ./scripts/run-local.sh
execute Guake GTK3 for developer.
bash: line 5: pew: command not found
Using guake image directory: /home/pleycpl/Documents/github/Guake/guake/guake/po
Using guake data directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake image directory: /home/pleycpl/Documents/github/Guake/guake/guake/data/pixmaps
Using guake data directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake glade directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake data directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake scheme directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake data directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake theme directory: /home/pleycpl/Documents/github/Guake/guake/guake/data/theme
Traceback (most recent call last):
  File "guake/main.py", line 400, in <module>
    exec_main()
  File "guake/main.py", line 388, in exec_main
    if not main():
  File "guake/main.py", line 259, in main
    import dbus
ModuleNotFoundError: No module named 'dbus'
Done
```

```bash
$ python
Python 3.6.5 (default, May 11 2018, 04:00:52) 
[GCC 8.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dbus
>>> dir(dbus)
['Array', 'BUS_DAEMON_IFACE', 'BUS_DAEMON_NAME', 'BUS_DAEMON_PATH', 'Boolean', 'Bus', 'Byte', 'ByteArray', 'DBusException', 'Dictionary', 'Double', 'INTROSPECTABLE_IFACE', 'Int16', 'Int32', 'Int64', 'Interface', 'IntrospectionParserException', 'LOCAL_IFACE', 'LOCAL_PATH', 'MissingErrorHandlerException', 'MissingReplyHandlerException', 'NameExistsException', 'ObjectPath', 'PEER_IFACE', 'PROPERTIES_IFACE', 'SessionBus', 'Signature', 'StarterBus', 'String', 'Struct', 'SystemBus', 'UInt16', 'UInt32', 'UInt64', 'UnknownMethodException', 'ValidationException', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_compat', '_dbus', '_expat_introspect_parser', 'bus', 'connection', 'exceptions', 'get_default_main_loop', 'is_py2', 'lowlevel', 'proxies', 'set_default_main_loop', 'types', 'validate_bus_name', 'validate_error_name', 'validate_interface_name', 'validate_member_name', 'validate_object_path', 'version']
```

```bash
$ sudo pacman -Q --info python-dbus
Name            : python-dbus
Version         : 1.2.8-1
Description     : Python 3.6 bindings for DBUS
Architecture    : x86_64
URL             : https://www.freedesktop.org/wiki/Software/DBusBindings
Licenses        : GPL  LGPL
Groups          : None
Provides        : None
Depends On      : dbus  glib2  python-dbus-common  python
Optional Deps   : None
Required By     : gnome-code-assistance  guake  orca
Optional For    : avahi  libpurple  totem
Conflicts With  : None
Replaces        : None
Installed Size  : 541.00 KiB
Packager        : Jan de Groot <jgc@archlinux.org>
Build Date      : Thu 21 Jun 2018 01:28:16 AM +03
Install Date    : Thu 05 Jul 2018 11:38:23 AM +03
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by gsemet** [comment]
`bash: line 5: pew: command not found``

You might need to reinstall the basis dependencies: `pip install --user pip pipenv pbr`

**Comment by pleycpl** [comment]
Nothing change.
```bash
➜  guake git:(master) pip install --user pip pipenv pbr        
Requirement already satisfied: pip in /usr/lib/python3.6/site-packages (10.0.1)
Requirement already satisfied: pipenv in /home/pleycpl/.local/lib/python3.6/site-packages (2018.7.1)
Requirement already satisfied: pbr in /usr/lib/python3.6/site-packages (4.1.0)
Requirement already satisfied: certifi in /usr/lib/python3.6/site-packages (from pipenv) (2018.4.16)
Requirement already satisfied: virtualenv in /usr/lib/python3.6/site-packages (from pipenv) (16.0.0)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /usr/lib/python3.6/site-packages (from pipenv) (0.3.0)
Requirement already satisfied: setuptools>=36.2.1 in /usr/lib/python3.6/site-packages (from pipenv) (39.2.0)
➜  guake git:(master) make run      
rm -f /home/pleycpl/Documents/github/Guake/guake/data/gschemas.compiled
glib-compile-schemas --strict /home/pleycpl/Documents/github/Guake/guake/data
pipenv run ./scripts/run-local.sh
execute Guake GTK3 for developer.
bash: line 5: pew: command not found
Using guake image directory: /home/pleycpl/Documents/github/Guake/guake/guake/po
Using guake data directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake image directory: /home/pleycpl/Documents/github/Guake/guake/guake/data/pixmaps
Using guake data directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake glade directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake data directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake scheme directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake data directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake theme directory: /home/pleycpl/Documents/github/Guake/guake/guake/data/theme
Traceback (most recent call last):
  File "guake/main.py", line 400, in <module>
    exec_main()
  File "guake/main.py", line 388, in exec_main
    if not main():
  File "guake/main.py", line 259, in main
    import dbus
ModuleNotFoundError: No module named 'dbus'
Done
```

**Comment by gsemet** [comment]
Pip install —user pew ?

**Comment by pleycpl** [comment]
```bash
➜  guake git:(master) pip install --user pip pipenv pbr pew
Requirement already satisfied: pip in /usr/lib/python3.6/site-packages (10.0.1)
Requirement already satisfied: pipenv in /home/pleycpl/.local/lib/python3.6/site-packages (2018.7.1)
Requirement already satisfied: pbr in /usr/lib/python3.6/site-packages (4.1.0)
Requirement already satisfied: pew in /home/pleycpl/.local/lib/python3.6/site-packages (1.1.5)
Requirement already satisfied: virtualenv in /usr/lib/python3.6/site-packages (from pipenv) (16.0.0)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /usr/lib/python3.6/site-packages (from pipenv) (0.3.0)
Requirement already satisfied: certifi in /usr/lib/python3.6/site-packages (from pipenv) (2018.4.16)
Requirement already satisfied: setuptools>=36.2.1 in /usr/lib/python3.6/site-packages (from pipenv) (39.2.0)
➜  guake git:(master) make run
rm -f /home/pleycpl/Documents/github/Guake/guake/data/gschemas.compiled
glib-compile-schemas --strict /home/pleycpl/Documents/github/Guake/guake/data
pipenv run ./scripts/run-local.sh
execute Guake GTK3 for developer.
bash: line 5: pew: command not found
Using guake image directory: /home/pleycpl/Documents/github/Guake/guake/guake/po
Using guake data directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake image directory: /home/pleycpl/Documents/github/Guake/guake/guake/data/pixmaps
Using guake data directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake glade directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake data directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake scheme directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake data directory: /home/pleycpl/Documents/github/Guake/guake/guake/data
Using guake theme directory: /home/pleycpl/Documents/github/Guake/guake/guake/data/theme
Traceback (most recent call last):
  File "guake/main.py", line 400, in <module>
    exec_main()
  File "guake/main.py", line 388, in exec_main
    if not main():
  File "guake/main.py", line 259, in main
    import dbus
ModuleNotFoundError: No module named 'dbus'
Done
```

**Comment by gsemet** [comment]
You probably have a conflict between python2 and python3 version of pip, pipenv, pew,... please uninstall pew and pipenv from your python 2 user env

**Comment by pleycpl** [comment]
Should we install PEW package as a dependency?

@aichingm `pacman -S python-pew`
https://github.com/Guake/guake/blob/master/scripts/bootstrap-dev-arch.sh#L36

**Comment by aichingm** [comment]
Ah okay, didn't know that! I think if it is installed via `make dev` already, it should be alright.
