### ISSUE TITLE
guake --execute-command exception

### ISSUE THREAD

**Issue by antondemanoff** [Guake/guake#1365]
guake fails while executing `guake -e 'ls -l'`
Linux Mint 19
Gnome 3.28.2
Python 3.6.5
```
Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3/dist-packages/guake/main.py", line 356, in exec_main
    if not main():
  File "/usr/lib/python3/dist-packages/guake/main.py", line 297, in main
    remote_object.execute_command(options.command)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/guake/dbusiface.py", line 103, in execute_command
    self.guake.execute_command(command)
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 549, in execute_command
    terminal.feed_child(command, len(command))
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_guake.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3/dist-packages/guake/main.py", line 356, in exec_main
    if not main():
  File "/usr/lib/python3/dist-packages/guake/main.py", line 297, in main
    remote_object.execute_command(options.command)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/guake/dbusiface.py", line 103, in execute_command
    self.guake.execute_command(command)
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 549, in execute_command
    terminal.feed_child(command, len(command))
TypeError: Vte.Terminal.feed_child() takes exactly 2 arguments (3 given)
```

**Comment by gsemet** [comment]
Can you tell me your version of VTE ?

**Comment by antondemanoff** [comment]
@gsemet, VTE version 0.52.2

**Comment by dorian-marchal** [comment]
Same error, here.

**Comment by gsemet** [comment]
Which version of Guake? Should not happen on 3.2.x

**Comment by gsemet** [comment]
You can install guake from pip :)
```bash
pip3 install --user --upgrade guake
```

**Comment by antondemanoff** [comment]
Okey, thanks. I'l be waiting for next stable release by Ubuntu maintainers.

**Comment by Davidy22** [comment]
Does not occur in git master, and was fixed some time ago in older version of guake so closing.
