### ISSUE TITLE
guake --fgcolor error

### ISSUE THREAD

**Issue by flo2k** [Guake/guake#1376]
Hello,

when I use

```bash
guake --fgcolor=#1E7E1A
```
I get the following error:

```bash
$ guake --fgcolor=#1E7E1A
Using guake image directory: /home/xxx/.local/share/guake/po
Using guake data directory: /home/xxx/.local/share/guake/data
Using guake image directory: /home/xxx/.local/share/guake/data/pixmaps
Using guake data directory: /home/xxx/.local/share/guake/data
Using guake glade directory: /home/xxx/.local/share/guake/data
Using guake data directory: /home/xxx/.local/share/guake/data
Using guake scheme directory: /home/xxx/.local/share/guake/data
Using guake data directory: /home/xxx/.local/share/guake/data
Using guake theme directory: /home/xxx/.local/share/guake/data/theme
Traceback (most recent call last):
  File "/home/xxx/.local/bin/guake", line 11, in <module>
    sys.exit(exec_main())
  File "/home/xxx/.local/lib/python3.6/site-packages/guake/main.py", line 388, in exec_main
    if not main():
  File "/home/xxx/.local/lib/python3.6/site-packages/guake/main.py", line 344, in main
    remote_object.set_fgcolor(options.fgcolor)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/home/xxx/.local/lib/python3.6/site-packages/guake/dbusiface.py", line 99, in set_fgcolor
    self.guake.set_fgcolor(fgcolor)
AttributeError: 'Guake' object has no attribute 'set_fgcolor'
```

Guake Version:
```bash
flo@flo-nbw:/data/downloads$ guake --version
Using guake image directory: /home/xxx/.local/share/guake/po
Using guake data directory: /home/xxx/.local/share/guake/data
Using guake image directory: /home/xxx/.local/share/guake/data/pixmaps
Using guake data directory: /home/xxx/.local/share/guake/data
Using guake glade directory: /home/xxx/.local/share/guake/data
Using guake data directory: /home/xxx/.local/share/guake/data
Using guake scheme directory: /home/xxx/.local/share/guake/data
Using guake data directory: /home/xxx/.local/share/guake/data
Using guake theme directory: /home/xxx/.local/share/guake/data/theme
Guake Terminal: 3.3.2
VTE: 0.52.2
VTE runtime: 0.52.2
Gtk: 3.22.30
```

System version:
```bash
$ uname -a
Linux xxx 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/issue.net 
Linux Mint 19 Tara
```

**Comment by aichingm** [comment]
`set_bgcolor` and `set_bg_image` are also affected I guess I removed/renamed them when porting guake to GTK3 and forgot about the dbus interface. Sorry about that I will fix it!
