### ISSUE TITLE
Unable to complile guake on Ubuntu 14.04

### ISSUE THREAD

**Issue by kirtangajjar** [Guake/guake#1383]
```
╰─± sudo make
generating desktop files
msgfmt: unrecognized option '--desktop'
Try 'msgfmt --help' for more information.
Skipping .desktop files, is your gettext version < 0.19.1?
msgfmt: unrecognized option '--desktop'
Try 'msgfmt --help' for more information.
Skipping .desktop files, is your gettext version < 0.19.1?
Generating path.py...
generating po/uk.po
generating po/tr.po
generating po/de.po
generating po/fa.po
generating po/pt_BR.po
generating po/fr.po
generating po/ja.po
generating po/sv.po
generating po/cs.po
generating po/el.po
generating po/nl.po
generating po/pa.po
generating po/id.po
generating po/nb.po
generating po/ko.po
generating po/ca.po
generating po/es.po
generating po/hr.po
generating po/it.po
generating po/ru.po
generating po/hu.po
generating po/pl.po
generating po/zh_CN.po
generating po/gl.po
rm -f /home/admin-pc/code/temp/guake/data/gschemas.compiled
glib-compile-schemas --strict /home/admin-pc/code/temp/guake/data
# 'make' target, so users can install guake without need to install the 'dev' dependencies
```

```
╰─± sudo make install                                  
install -Dm644 "/home/admin-pc/code/temp/guake/data/guake.desktop" "//usr/local/share/applications/guake.desktop"
install -Dm644 "/home/admin-pc/code/temp/guake/data/guake-prefs.desktop" "//usr/local/share/applications/guake-prefs.desktop"
mkdir -p //usr/local/share/guake/pixmaps
install -Dm644 /home/admin-pc/code/temp/guake/data/pixmaps/*.png "//usr/local/share/guake/pixmaps/"
install -Dm644 /home/admin-pc/code/temp/guake/data/pixmaps/*.svg "//usr/local/share/guake/pixmaps/"
install -Dm644 /home/admin-pc/code/temp/guake/data/pixmaps/guake.png "//usr/local/share/pixmaps/guake.png"
mkdir -p //usr/local/share/guake
mkdir -p //usr/local/share/guake
install -Dm644  /home/admin-pc/code/temp/guake/data/*.glade "//usr/local/share/guake"
mkdir -p //usr/local/share/guake
install -Dm644 "/home/admin-pc/code/temp/guake/data/autostart-guake.desktop" "//usr/local/share/guake"
mkdir -p //usr/local/share/glib-2.0/schemas
install -Dm644 "/home/admin-pc/code/temp/guake/data/org.guake.gschema.xml" "//usr/local/share/glib-2.0/schemas/"
if [ 1 = 1 ]; then glib-compile-schemas //usr/local/share/glib-2.0/schemas; fi
for f in $(find po -iname "*.mo"); do \
		l="${f%%.*}"; \
		lb=$(basename $l); \
		install -Dm644 "$f" "//usr/local/share/locale/$lb/LC_MESSAGES/guake.mo"; \
	done;
# you probably want to execute this target with sudo:
# sudo make install
Installing from on your system is not recommended.
Please prefer you application package manager (apt, yum, ...)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 262, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1632, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python3/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', "typing ; python_version < '3.5'", 'at', " ; python_version < '3.5'")

Storing debug log for failure in /home/admin-pc/.pip/pip.log
make: *** [install-guake] Error 2
```

If you need additional details, ping me

**Comment by aichingm** [comment]
Looks like your python version is lower than 3.5. What does `python3 --version` print?

Btw: why are you using a 4 year old ubuntu version?

**Comment by kirtangajjar** [comment]
No issues. I'll upgrade python.
