### ISSUE TITLE
Can't start up in Gnome Wayland

### ISSUE THREAD

**Issue by 0kaguya** [Guake/guake#1581]
Guake version: 3.6.2
Environment: Archlinux, Gnome Shell 3.32.1 on wayland

error message:
``` bash
$guake
Guake not running, starting it
Guake Terminal 3.6.2
VTE 0.56.2
Gtk 3.24.8

(guake:9414): Wnck-WARNING **: 16:16:43.728: libwnck is designed to work in X11 only, no valid display found
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/guake/main.py", line 359, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3.7/site-packages/guake/main.py", line 488, in exec_main
    if not main():
  File "/usr/lib/python3.7/site-packages/guake/main.py", line 374, in main
    instance = Guake()
  File "/usr/lib/python3.7/site-packages/guake/guake_app.py", line 183, in __init__
    self.page_deleted
  File "/usr/lib/python3.7/site-packages/guake/notebook.py", line 364, in __init__
    self.screen.connect("active-workspace-changed", self.workspace_changed)
AttributeError: 'NoneType' object has no attribute 'connect'
```

**Comment by 0kaguya** [comment]
It happens after recent update. Is `libwnck` a new introduced dependency?

**Comment by mlouielu** [comment]
Yes, wnck is a needed dependency. (For NotebookManager)

For ArchLinux, it is list on the dependencies:
https://www.archlinux.org/packages/community/any/guake/

kaguya houraisan <notifications@github.com> 於 2019年5月4日 週六 16:25 寫道：

**Comment by gsemet** [comment]
Indeed

**Comment by mlouielu** [comment]
But I think the problem is because Wayland, see the first line of the
traceback: libwnck is designed to work in X11 only, no valid display found.
This causing self.screen not initialize successfully.

Not sure if it is only about Wayland or with libwnck depdency, I'll take a
test next Monday.

Gaetan Semet <notifications@github.com> 於 2019年5月4日 週六 19:28 寫道：

**Comment by gsemet** [comment]
I am a bit sick about the wayland is incompatible with pretty much every existing useful lib. I mean, I get they wanted something more modern and more elegant, but you keep “backward” compatibility somehow. Since I donot use it I cannot test any change and even ensure guake on wayland still work

**Comment by mlouielu** [comment]
I can confirm this on master `HEAD` by:

```
$ weston  # Open up weston compositor
[ Inside weston compositor ]
$ make run
(guake:13379): Wnck-WARNING **: libwnck is designed to work in X11 only, no valid display found
Traceback (most recent call last):
```
