### ISSUE TITLE
Crash when closing tab with shortcut on ubuntu 19.04  

### ISSUE THREAD

**Issue by Korydween** [Guake/guake#1586]
Hi there, 

I have been using guake for years without problems, but I recently upgraded to Ubuntu 19.04 and got problem with the shortcut to close a tab. My current version is guake 3.4.0-1. 

Why using the shortcut (default one), the tab does not close and it sends an ubuntu internal bug report with these details: 

`ProcVersionSignature: Ubuntu 5.0.0-13.14-generic 5.0.6
Python3Details: /usr/bin/python3.7, Python 3.7.3, python3-minimal, 3.7.3-1
PythonDetails: /usr/bin/python2.7, Python 2.7.16, python-minimal, 2.7.16-1
SourcePackage: guake
Tags:  disco
Title: guake crashed with TypeError: delete_page_current() takes from 1 to 2 positional arguments but 5 were given
Uname: Linux 5.0.0-13-generic x86_64
UpgradeStatus: No upgrade log present (probably fresh install)
_MarkForUpload: True
`

Closing a tab by right-clicking and clicking on "close" works flawlessly. 
I tried to compile from source, the tab still does not close but I don't receive the crash report from Ubuntu anymore.

**Comment by gsemet** [comment]
You should update to latest version (pip install —user) it should be fixed

**Comment by Korydween** [comment]
I have installed guake using apt. I just reinstalled and now guake does not start anymore :( 
`Guake not running, starting it
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/guake/main.py", line 359, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/local/lib/python3.7/dist-packages/guake/main.py", line 488, in exec_main
    if not main():
  File "/usr/local/lib/python3.7/dist-packages/guake/main.py", line 374, in main
    instance = Guake()
  File "/usr/local/lib/python3.7/dist-packages/guake/guake_app.py", line 134, in __init__
    super(Guake, self).__init__(gladefile('guake.glade'))
  File "/usr/local/lib/python3.7/dist-packages/guake/common.py", line 65, in gladefile
    raise IOError('No such file or directory: %s' % f)
OSError: No such file or directory: /usr/local/share/guake/guake.glade
`

**Comment by mlouielu** [comment]
Is because new version (> 3.6.1) change the data directory path.

You will need to clone the repo, and compile, install new data directory.

$ git clone https://github.com/guake/guake
$ cd guake
$ make
$ make install   # may need root privilege



Korydween <notifications@github.com> 於 2019年5月9日 週四 21:24 寫道：
