### ISSUE TITLE
Startup error on Kubuntu 19.10.

### ISSUE THREAD

**Issue by Rivand** [Guake/guake#1668]
Just installed Kubuntu 19.10, and guake on it (from the standard repository: apt install guake). Guake not starting. When I trying to start guake from terminal, an error occurs:

    oem@Kubuntu19:~$ guake
    Guake not running, starting it
    Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
        return self.get_name_owner(bus_name)
    File "/usr/lib/python3/dist-packages/dbus/bus.py", line 363, in get_name_owner
        's', (bus_name,), **keywords)
    File "/usr/lib/python3/dist-packages/dbus/connection.py", line 653, in call_blocking
        message, timeout)
    dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/guake/main.py", line 359, in main
        remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
    File "/usr/lib/python3/dist-packages/dbus/bus.py", line 243, in get_object
        follow_name_owner_changes=follow_name_owner_changes)
    File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
        self._named_service = conn.activate_name_owner(bus_name)
    File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
        self.start_service_by_name(bus_name)
    File "/usr/lib/python3/dist-packages/dbus/bus.py", line 280, in start_service_by_name
        'su', (bus_name, flags)))
    File "/usr/lib/python3/dist-packages/dbus/connection.py", line 653, in call_blocking
        message, timeout)
    dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/usr/bin/guake", line 10, in <module>
        sys.exit(exec_main())
    File "/usr/lib/python3/dist-packages/guake/main.py", line 488, in exec_main
        if not main():
    File "/usr/lib/python3/dist-packages/guake/main.py", line 373, in main
        from guake.guake_app import Guake
    File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 72, in <module>
        from guake.notebook import NotebookManager

Guake Terminal: 3.6.3
VTE: 0.58.2
VTE runtime: 0.58.2
Gtk: 3.24.12

**Comment by gsemet** [comment]
Look like the dbus is not registered. Maybe restart ?

**Comment by Rivand** [comment]
> Look like the dbus is not registered. Maybe restart ?

What exactly to restart?

**Comment by gsemet** [comment]
Your pc. It may register the missing channel. Or reinstall completely from pip install guake

**Comment by Rivand** [comment]
Reinstalling via pip did not help.

**Comment by robert-matusewicz** [comment]
@Rivand this issue is very similar to #1511 - could you try to

`apt install gir1.2-wnck-3.0`

and check if that will fix your problem?

**Comment by Sandman0984** [comment]
> @Rivand this issue is very similar to #1511 - could you try to
> 
> `apt install gir1.2-wnck-3.0`
> 
> and check if that will fix your problem?
> 
> Guake package in Ubuntu <= 19.10 does not correctly tag that package as dependency

Confirmed this is still an issue, Kubuntu 19.10, Guake 3.6.3-1.  Installing the 'gir1.2-wnck-3.0' package solved the issue.

**Comment by j-jeurissen** [comment]
yes, apt install gir1.2-wnck-3.0 fixed it

**Comment by Davidy22** [comment]
Packaging issue that should be resolved by the repos now, closing.
