### ISSUE TITLE
"Failed to open PTY: Too many open files" error on startup

### ISSUE THREAD

**Issue by Zazcallabah** [Guake/guake#1691]
**Describe the bug**

guake won't start. I had it working for several months, but I think it broke after an apt-get upgrade of -something-. I'm on Kubuntu 19.04, with guake installed via apt.

**Actual behavior**
```
~$ guake
Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3/dist-packages/guake/main.py", line 488, in exec_main
    if not main():
  File "/usr/lib/python3/dist-packages/guake/main.py", line 465, in main
    remote_object.show_hide()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.gi.repository.GLib.Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
  File "/usr/lib/python3/dist-packages/guake/dbusiface.py", line 45, in show_hide
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 460, in show_hide
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 552, in show
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 964, in add_tab
  File "/usr/lib/python3/dist-packages/guake/notebook.py", line 204, in new_page_with_focus
  File "/usr/lib/python3/dist-packages/guake/notebook.py", line 170, in new_page
  File "/usr/lib/python3/dist-packages/guake/notebook.py", line 196, in terminal_spawn
  File "/usr/lib/python3/dist-packages/guake/terminal.py", line 498, in spawn_sync_pid
gi.repository.GLib.GError: g-io-error-quark: Failed to open PTY: Too many open files (31)
```
-------------------------------------------------------------------------------
<details><summary>$ guake --support</summary>

Guake Version:          3.6.3

Vte Version:            0.56.2

Vte Runtime Version:    0.56.2

--------------------------------------------------
GTK+ Version:           3.24.8

GDK Backend:            GdkX11.X11Display

--------------------------------------------------
Desktop Session: plasma

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 -  eDP-1
    * Geometry:         1920 x 1080 at 0, 0
    * Size:             344 x 194 mm²
    * Primary:          True
    * Refresh rate:     119.94 Hz
    * Subpixel layout:  unknown

**Comment by Zazcallabah** [comment]
Changing the system open files limit as described [here](https://www.robustperception.io/dealing-with-too-many-open-files) doesnt help. But logging out and logging in again does make the problem go away for a little while.

If guake is already running when whatever happens happens that triggers the problem, then the existing tabs work, but using keyboard shortcuts to resize guake or change the opacity doesn't. Also you can't open new tabs.

**Comment by deadanon** [comment]
Also having this problem here's an error dump:
```guake --version
Guake Terminal: 3.6.3
VTE: 0.60.1
VTE runtime: 0.60.1
Gtk: 3.24.18
```
```
Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3/dist-packages/guake/main.py", line 488, in exec_main
    if not main():
  File "/usr/lib/python3/dist-packages/guake/main.py", line 465, in main
    remote_object.show_hide()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.gi.repository.GLib.Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 711, in _message_cb
  File "/usr/lib/python3/dist-packages/guake/dbusiface.py", line 45, in show_hide
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 494, in show_hide
    self.show()
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 602, in show
    self.add_tab()
  File "/usr/lib/python3/dist-packages/guake/utils.py", line 73, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 1051, in add_tab
    self.get_notebook().new_page_with_focus(directory)
  File "/usr/lib/python3/dist-packages/guake/notebook.py", line 264, in new_page_with_focus
    box, page_num, terminal = self.new_page(directory)
  File "/usr/lib/python3/dist-packages/guake/notebook.py", line 224, in new_page
    terminal = self.terminal_spawn(directory)
  File "/usr/lib/python3/dist-packages/guake/notebook.py", line 256, in terminal_spawn
    terminal.spawn_sync_pid(directory)
  File "/usr/lib/python3/dist-packages/guake/terminal.py", line 534, in spawn_sync_pid
    pid = self.spawn_sync(
gi.repository.GLib.GError: g-io-error-quark: Failed to open PTY: Too many open files (31)
```

**Comment by jpcasas** [comment]
I solved killing an already open process with guake
the commands:
ps -aux | grep python

this process show it 
/usr/bin/python3 /usr/bin/guake

i kill it with 

kill -9 <idprocess>

and i restarted the guake

**Comment by zeusintuivo** [comment]
This can also be closed. This is a linux issue not Guake  issue
the fix is in this link https://bobcares.com/blog/too-many-open-files/ 
If you are using Visual Studio Code or Sublime or JetBrains something, these open lots of files to observe. Also if you have many services and watchers
@Davidy22

**Comment by Davidy22** [comment]
Yeah looks about right, closing. Hardware's probably advanced since the original file limit was set, might be nice for them to reconsider for the tab hoarders out there now that we're all on burly machines with spacious ram

**Comment by Zazcallabah** [comment]
I mean, are you pushing "linux" for a bugfix on this? An actively developed tool has a much louder voice than a lone user.

**Comment by Davidy22** [comment]
Even guake probably doesn't have that much sway on the kernel devs, the current default file limit is pretty spacious too. I can chip in on a dogpile on the file limit if file open limits start being a problem for more people and I'm sure it'll move eventually as the lowest common denominator computer gets better. For now though, you can follow the link above to bump limits on your own computer if you want more flex room to have a healthy amount of editor tabs open on your machine
