### ISSUE TITLE
Window gets transparent when I turn the terminal on and off too fast

### ISSUE THREAD

**Issue by blamoo** [Guake/guake#1707]
The window gets totally transparent if I hold F12 for some seconds. I'm still able to type commands, select text and access the right click menu on the transparent terminal.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.42.5

Vte Runtime Version:	0.42.5

--------------------------------------------------
GTK+ Version:		3.18.9

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

Traceback (most recent call last):
  File "/home/soler/.local/bin/guake", line 11, in <module>
    sys.exit(exec_main())
  File "/home/soler/.local/lib/python3.5/site-packages/guake/main.py", line 488, in exec_main
    if not main():
  File "/home/soler/.local/lib/python3.5/site-packages/guake/main.py", line 342, in main
    print_support()
  File "/home/soler/.local/lib/python3.5/site-packages/guake/support.py", line 103, in print_support
    get_display()
  File "/home/soler/.local/lib/python3.5/site-packages/guake/support.py", line 95, in get_display
    populate_display(display)
  File "/home/soler/.local/lib/python3.5/site-packages/guake/support.py", line 33, in populate_display
    n_monitors = display.get_n_monitors()
AttributeError: 'X11Display' object has no attribute 'get_n_monitors'

**Comment by Davidy22** [comment]
Unable to reproduce, are you still seeing this issue?

**Comment by blamoo** [comment]
> Unable to reproduce, are you still seeing this issue?

I bought a new graphics card, monitor and upgraded to Ubuntu 20 LTS (from 18 LTS) this year... I also can't reproduce the problem anymore so it looks like it's gone.

**Comment by Davidy22** [comment]
Alright, will close then.
