### ISSUE TITLE
Guake does not auto-launch on computer boot in Ubuntu 20.04

### ISSUE THREAD

**Issue by GaurangTandon** [Guake/guake#1785]
Everytime I restart my pc, I have to manually launch Guake on boot. Here is my settings screenshot:

![image](https://user-images.githubusercontent.com/6308683/88053114-ecf1b900-cb78-11ea-8404-9c8f7b5d313c.png)

As you can see "Start Guake on login" is checked, so I am not sure what else to do.

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - BOE eDP-1
    * Geometry:		1360 x 768 at 0, 0
    * Size:		344 x 193 mm²
    * Primary:		True
    * Refresh rate:	59.96 Hz
    * Subpixel layout:	unknown

**Comment by GaurangTandon** [comment]
I tried installing by `pipx` (for v3.7.0) but I can't run it, logs:

```
~ pipx install guake            
  installed package guake 3.7.0, Python 3.8.2
  These apps are now globally available
    - guake
    - guake-toggle
done! ✨ 🌟 ✨
~ guake-toggle   
Traceback (most recent call last):
  File "/home/gt/.local/bin/guake-toggle", line 8, in <module>
    sys.exit(toggle_guake_by_dbus())
  File "/home/gt/.local/pipx/venvs/guake/lib/python3.8/site-packages/guake/guake_toggle.py", line 2, in toggle_guake_by_dbus
    import dbus
ModuleNotFoundError: No module named 'dbus'
~ guake       
Traceback (most recent call last):
  File "/home/gt/.local/bin/guake", line 5, in <module>
    from guake.main import exec_main
  File "/home/gt/.local/pipx/venvs/guake/lib/python3.8/site-packages/guake/main.py", line 41, in <module>
    from guake.support import print_support
  File "/home/gt/.local/pipx/venvs/guake/lib/python3.8/site-packages/guake/support.py", line 5, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Comment by rccardero** [comment]
> Everytime I restart my pc, I have to manually launch Guake on boot. Here is my settings screenshot:
> 
> ![image](https://user-images.githubusercontent.com/6308683/88053114-ecf1b900-cb78-11ea-8404-9c8f7b5d313c.png)
> 
> As you can see "Start Guake on login" is checked, so I am not sure what else to do.
> 
> Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.
> 
> $ guake --support

I have the same problem in Ubuntu 20.04, and I have to manually launch Guake on boot, 
The output of the command is:
<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - CMN eDP-1
    * Geometry:		1366 x 768 at 0, 0
    * Size:		309 x 173 mm²
    * Primary:		True
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by xoxefdp** [comment]
Same case here, running Xubuntu 20.04

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: xubuntu

--------------------------------------------------
Display: :0.0

RGBA visual: True

Composited: True

* Monitor: 0 - AUO eDP
    * Geometry:		1366 x 768 at 0, 0
    * Size:		344 x 193 mm²
    * Primary:		True
    * Refresh rate:	60.05 Hz
    * Subpixel layout:	unknown

**Comment by kryo2k** [comment]
Same here, Ubuntu 20.04:

<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - SHP eDP-1
    * Geometry:		1920 x 1200 % 2 at 0, 0
    * Size:		288 x 180 mm²
    * Primary:		True
    * Refresh rate:	59.99 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
For @GaurangTandon, try the following commands:

```
sudo apt-get install python3-gi
pip install dbus
```

And that should resolve your dependency issues. dbus not installing as a dependency is probably an error, will check our packaging. For the others, you may not be experiencing the exact same issue as the original poster; can you run `guake` from a terminal and report back on the error message?

**Comment by GaurangTandon** [comment]
@Davidy22 Thanks for your response! Unfortunately, it seems dbus is not even a package on the pypi repo so I'm not sure how the pip install is going to work. When I run it I get the error:

```
ERROR: Could not find a version that satisfies the requirement dbus (from versions: none)
ERROR: No matching distribution found for dbus
```

as expected.

**Comment by Davidy22** [comment]
Oh, whoops, dbus-python. Should have import name dbus.

**Comment by Davidy22** [comment]
Hrm. For now, you can use `guake-toggle` in ubuntu's general startup programs menu, and we'll look into this a bit more

**Comment by Czaki** [comment]
> Hrm. For now, you can use ubuntu's general startup programs menu, and we'll look into this a bit more

No. As guake remove itself from startup programs.

I still need to launch guake manually on ubuntu 22.04:

<details><summary>$ guake --support</summary>

Guake Version:		3.8.5

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.33

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :1

RGBA visual: True

Composited: True

* Monitor: 0 - DEL DP-2
    * Geometry:		2560 x 1440 at 1920, 0
    * Size:		597 x 336 mm²
    * Primary:		True
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - BNQ HDMI-0
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		477 x 268 mm²
    * Primary:		False
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown
* Monitor: 2 - BNQ HDMI-1
    * Geometry:		1920 x 1080 at 4480, 0
    * Size:		477 x 268 mm²
    * Primary:		False
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown  
</details>

**Comment by Davidy22** [comment]
If the guake checkbox to open on startup doesn't work and guake doesn't show up on ubuntu's startup programs list, you can also try just setting the guake shell command to run at startup
