### ISSUE TITLE
Quick Open File Behavior (not as expected)

### ISSUE THREAD

**Issue by SeanPedersen** [Guake/guake#1825]
**Describe the bug**

Guake highlights and makes URL's clickable (CTRL + mouse) and opens them via xdg-open but the same behavior does not apply to file paths. Is that intended behavior? If so why hasn't it been added? That is a fundamental and **really useful feature** IMO.

**Expected behavior**

Highlight file paths just like URL's and make them clickable / openable using CTRL + mouse via xdg-open.

**Actual behavior**

No highlight, only if I myself highlight and right click can I use "Quick Open" option, which is very tedious compared to the existing URL workflow.

**To Reproduce**

Open Guake and run `readlink -f onanyfile`

**Comment by bruno-petit** [comment]
I have the same actual behavior on Debian 10 with Gnome 3.30 (and Wayland)
URL are clickable with CTRL + mouse but file paths are not...

**Comment by KonstantMan** [comment]
I have the same issue with guake on GNOME 40 X11 ARCH

**Comment by Davidy22** [comment]
Guake already has some amount of regular expression patterns that it will enable ctrl+click opening files for listed in the quick open tab in properties, although it could use some expansion to be more general.

**Comment by PhungXuanAnh** [comment]
I am looking forward this very usefull feature

**Comment by CristhianMotoche** [comment]
Hello there! I would like to take a look at this issue. However, I'm getting this error message when I try to run guake:

```
$ make run
rm -f /home/username/code/guake/guake/data/gschemas.compiled
glib-compile-schemas --strict /home/username/code/guake/guake/data
PIPENV_IGNORE_VIRTUALENVS=1 pipenv run ./scripts/run-local.sh
execute Guake GTK3 for developer.
Enabled global site-packages
Traceback (most recent call last):
  File "guake/main.py", line 54, in <module>
    from guake.support import print_support
  File "/home/username/code/guake/guake/support.py", line 5, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Done
```

FWIW:
```
$ uname -a
Linux computer 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

$ python --version
Python 3.6.15

$ apt list | grep python3-gi


python3-gi-cairo/jammy-updates 3.42.1-0ubuntu1 amd64
python3-gi-cairo/jammy-updates 3.42.1-0ubuntu1 i386
python3-gi-dbg/jammy-updates 3.42.1-0ubuntu1 amd64
python3-gi-dbg/jammy-updates 3.42.1-0ubuntu1 i386
python3-gi/jammy-updates,now 3.42.1-0ubuntu1 amd64 [installed]
python3-gi/jammy-updates 3.42.1-0ubuntu1 i386
...
```

Please, let me know if I may be missing something.

**Comment by raleik-pl** [comment]
Old case but seemed still valid.
So... It works for me, if I first select the text (file name/path), and then ctrl+click it.
Ubuntu 26.04 / Gnome 50 / Guake 3.10.1
Works even on folder paths - it opens the whole folder for me in vscode.
Or, if in the terminal text there's a filename followed by line number `some-file.txt:23` it highlights it on hover, and ctrl+clik works without selecting the text.
