### ISSUE TITLE
ImportError: cannot import name 'Sequence' from 'collections'

### ISSUE THREAD

**Issue by thegarlynch** [Guake/guake#1930]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

**Describe the bug**

Traceback (most recent call last):
  File "/usr/sbin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3.10/site-packages/guake/main.py", line 614, in exec_main
    if not main():
  File "/usr/lib/python3.10/site-packages/guake/main.py", line 440, in main
    from guake.dbusiface import DBUS_NAME
  File "/usr/lib/python3.10/site-packages/guake/dbusiface.py", line 25, in <module>
    import dbus.service
  File "/usr/lib/python3.10/site-packages/dbus/service.py", line 35, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Expected behavior**

**Actual behavior**

What you actually get.

**To Reproduce**

Provide the steps to reproduce the behavior

open guake in python3.10

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.64.2

Vte Runtime Version:	0.64.2

--------------------------------------------------
GTK+ Version:		3.24.30

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - CMN 0x14e3
    * Geometry:		1366 x 768 at 0, 0
    * Size:		310 x 170 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
The last line says that the error's coming out of dbus. Looks like dbus-python on pypi hasn't uploaded the version that they say is updated for python 3.10 yet as well. Their [pypi page](https://pypi.org/project/dbus-python/) does seem to suggest that we should use another python library, so switching to one of those shiny new options could be a thing too, would mean one more dependency on pure pypi too. I've made an issue on dbus-python's issue tracker to prompt them to update pypi, but until they update or we move away from dbus Guake does not yet support python 3.10.

**Comment by Davidy22** [comment]
Went googling a little and [this dbus option](https://github.com/altdesktop/python-dbus-next) seems fun, I'll try swapping this in sometime.

**Comment by thegarlynch** [comment]
Yeah. upgrading dbus-python worked

**Comment by PratyushBasu** [comment]
I'm unable to install/upgrade 'dbus-python' n Windows OS.
Error:
`error: [WinError 193] %1 is not a valid Win32 application
  ----------------------------------------
  ERROR: Failed building wheel for dbus-python
  Running setup.py clean for dbus-python
Failed to build dbus-python
Installing collected packages: dbus-python
    Running setup.py install for dbus-python ... error
    ERROR: Command errored out with exit status 1:`
    
Does this 'dbus-python' work in Windows OS also?
If not does anyone know the workaround?
Thanks in advance.

**Comment by Davidy22** [comment]
dbus is a library for connecting to a linux service. I was unaware that Guake worked on windows, have you been able to install it before?

**Comment by aussieklutz** [comment]
@dongyangTHU - You have asked about an error in a completely different project. This project has found a solution for it, but you likely need to go and check with the developers of whatever project you are using.

**Comment by dsaichand3** [comment]
Upgrading to the latest version of the pip worked for me.

**Comment by Guan-Smile** [comment]
`from collections.abc import Sequence`
It works!
https://github.com/wireservice/agate/pull/737

**Comment by GOLD106** [comment]
Exception ignored in thread started by: <function check_errors.<locals>.wrapper at 0x000001BB6B0E9480>
Traceback (most recent call last):
  File "C:\Users\GOLD\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\GOLD\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\GOLD\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "C:\Users\GOLD\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\GOLD\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\GOLD\AppData\Local\Programs\Python\Python310\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\GOLD\AppData\Local\Programs\Python\Python310\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\GOLD\AppData\Local\Programs\Python\Python310\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\GOLD\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\GOLD\AppData\Local\Programs\Python\Python310\lib\site-packages\corsheaders\__init__.py", line 1, in <module>
    from .checks import check_settings  # noqa: F401
  File "C:\Users\GOLD\AppData\Local\Programs\Python\Python310\lib\site-packages\corsheaders\checks.py", line 2, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (C:\Users\GOLD\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)

I have add the corsheader in setting.py
But I can see like this error.
How can I solve this error?

**Comment by GOLD106** [comment]
I have sent axios post request from reawct.js frontend to Django Backend.
 Because there is cors error, I have add the corsheader in Dhango.
