### ISSUE TITLE
Issue in the docs in Command Line Arguments

### ISSUE THREAD

**Issue by ravi-maithrey** [Guake/guake#1985]
I apologize if this is irrelevant and if readthedocs is no longer being actively updated, but I just noticed this.

**Describe the bug**

In the readthedocs site, the page for Command Line Arguments shows an error and not the actual usage of command line arguments. Link - [here](https://guake.readthedocs.io/en/latest/user/cli.html)

The actual text in the webpage is

> Here is the command line interface Guake provides:

> ```
>  Traceback (most recent call last):
>   File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/latest/bin/guake", line 10, in <module>
>      sys.exit(exec_main())
>    File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/latest/lib/python3.7/site-packages/guake/main.py", line 448, in exec_main
>      if not main():
>    File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/latest/lib/python3.7/site-packages/guake/main.py", line 272, in main
>      import gi
>  ModuleNotFoundError: No module named 'gi'
> ```

Attaching a picture, to make it clear

![image](https://user-images.githubusercontent.com/63500743/143897936-984a043c-3cb2-4147-96c0-68cce5070ff5.png)

**Expected behavior**

The actual command line arguments etc. should be present on this page

**Actual behavior**

The command line arguments etc. for guake are not on this page

**To Reproduce**

Go to [https://guake.readthedocs.io/en/latest/user/cli.html](https://guake.readthedocs.io/en/latest/user/cli.html)

**Comment by Davidy22** [comment]
The Guake readthedocs haven't been updating for a while. The one person with access to them is reportedly working on fixing it, although I have half a mind to just start a new account and change the links to there.

**Comment by ravi-maithrey** [comment]
Alright. If there's anyway I can help, let me know

**Comment by Davidy22** [comment]
I can't have you help with the current readthedocs because I don't have access to it either, @gsemet how's the progress on fixing the readthedocs build?

**Comment by meator** [comment]
I have also stumbled upon this issue. If the readthedocs documentation is no longer reliable, it should be removed from the project's README.
