### ISSUE TITLE
It takes tens of seconds before it can be used when start

### ISSUE THREAD

**Issue by feilongfl** [Guake/guake#1998]
**Describe the bug**

It takes tens of seconds before it can be used when start.
when I check the log, I find a `org.freedesktop.DBus.Error.NoReply` error.

**Expected behavior**

I think this program should not generate this error when it is opened, and it can be used immediately

**What you actually get**

It takes tens of seconds before it can be used when start.
log:
``` shell
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
 ~  guake
Guake not running, starting it
Loading Gnome schema from: /usr/share/glib-2.0/schemas
Language previously loaded from: /usr/share/locale
Guake Terminal 3.8.1
VTE 0.66.2
Gtk 3.24.30
created fresh notebook for workspace 0
Spawning new terminal at /home/feilong

(guake:174223): VTE-WARNING **: 06:22:17.040: (../vte/src/vtepty.cc:667):bool _vte_pty_spawn_sync(VtePty*, const char*, const char* const*, const char* const*, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, GPid*, int, GCancellable*, GError**): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
current workspace is 0
can't bind show-focus key
Guake initialized
Calling startup script: guake -e /usr/bin/tmux-auto
Startup script started with pid: <Popen: returncode: None args: ['guake -e /usr/bin/tmux-auto']>
ERROR:dbus.proxies:Introspect error on :1.214:/org/guake3/RemoteControl: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3.9/site-packages/guake/main.py", line 616, in exec_main
    if not main():
  File "/usr/lib/python3.9/site-packages/guake/main.py", line 535, in main
    remote_object.execute_command(options.command)
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Provide the steps to reproduce the behavior**

I got this error just startup this program.
I think except startup hook,I don't change any unusual config.
so I put this start up hook script here.
if you need more info, just let me know :smile: 

<details><summary>startup hook script - /usr/bin/tmux-auto</summary>

``` shell
#!/usr/bin/env fish
# use this script to keep a easy attach tmux session.

set sess "feilong"
set win "OverView"

if not tmux has-session -t $sess
    # pan -> nmon
    tmux set-option history-limit 100
    tmux new-session -A -c /home/feilong -s $sess -n $win -d

    tmux send-keys -t $sess -t $win 'nmon' C-m
    tmux send-keys -t $sess -t $win 'DmnjJk.'

    #pan -> welcome
    tmux set-option history-limit 10000
    tmux split-window -h -p 80 -t $sess -t $win
    tmux send-keys -t $sess -t $win 'neofetch' C-m
    tmux send-keys -t $sess -t $win 'echo Welcome! | cowsay' C-m

    #pan -> htop
    tmux set-option history-limit 100
    tmux split-window -h -p 30 -t $sess -t $win
    tmux send-keys -t $sess -t $win 'htop' C-m

    #pan -> nload
    tmux split-window -v -p 40 -t $sess -t $win
    tmux send-keys -t $sess -t $win 'nload' C-m

    #pan -> music
    tmux split-window -v -p 40 -t $sess -t $win
    tmux send-keys -t $sess -t $win 'watch -tn1 --color \'date +"%H:%M:%S" | toilet --filter rainbow -t --font mono9\'' C-m
    #tmux send-keys -t $sess -t $win 'cmus' C-m
    #tmux send-keys -t $sess -t $win 'x'

    # fin
    tmux select-pan -t $sess -t $win -t 2
    tmux select-window -t $sess -t $win
    tmux set-option history-limit 5000
end

tmux attach -t $sess
```
</details>

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

<details><summary>$ guake --support</summary>

Guake Version:		3.8.1

Vte Version:		0.66.2

Vte Runtime Version:	0.66.2

--------------------------------------------------
GTK+ Version:		3.24.30

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: regolith

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - DisplayPort-1
    * Geometry:		2560 x 1440 at 0, 0
    * Size:		708 x 399 mm²
    * Primary:		True
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - DVI-D-0
    * Geometry:		1920 x 1080 at 2560, 0
    * Size:		477 x 268 mm²
    * Primary:		False
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown

**Comment by feilongfl** [comment]
sorry for duplicate issues with #1982 .

At first I search `org.freedesktop.DBus.Error.NoReply` and find nothing,so I think it have not report yet.
