### ISSUE TITLE
fix document generation on readthedoc

### ISSUE THREAD

**Issue by gsemet** [Guake/guake#2033]
Failure on readthedoc:
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 308, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 415, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 436, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 476, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/sphinx/io.py", line 189, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/sphinx/io.py", line 109, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/sphinx/parsers.py", line 101, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/statemachine.py", line 240, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 3008, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/statemachine.py", line 240, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2097, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/reno/sphinxext.py", line 114, in run
    with loader.Loader(conf) as ldr:
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/reno/loader.py", line 62, in __init__
    self._load_data()
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/reno/loader.py", line 89, in _load_data
    self._scanner_output = self._scanner.get_notes_by_version()
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/reno/scanner.py", line 994, in get_notes_by_version
    earliest_version))
ValueError: earliest-version set to unknown revision '3.0.0.a4'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/stable/lib/python3.7/site-packages/reno/scanner.py", line 994, in get_notes_by_version
    earliest_version))
ValueError: earliest-version set to unknown revision '3.0.0.a4'
The full traceback has been saved in /tmp/sphinx-err-t0_th1iv.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Look like it does not check out enough commit

**Comment by Davidy22** [comment]
As the only person with the password, you're the only person who can fix this. We can't even help troubleshoot for you because you're the only person with access.

**Comment by gsemet** [comment]
yes, I fix it by disabling release notes auto generation (50 git depth limit by rtd). This part is buggy, we need to rework it.

**Comment by gsemet** [comment]
Fixed: https://guake.readthedocs.io/en/latest/project/index.html

**Comment by Davidy22** [comment]
Oh nice finally, I'll go back through issues because there's some amount related to this I remember

**Comment by gsemet** [comment]
Fixed by doing the release notes generation manually from now.
