### ISSUE TITLE
guake crashes when launched with -e parameter, "AttributeError: 'DbusManager' object has no attribute 'execute_command'"

### ISSUE THREAD

**Issue by julikaiba** [Guake/guake#2050]
**Describe the bug**

When starting guake with the -e parameter and anything other than an empty string after it guake crashes.

**Expected behavior**

guake starts with the command executing

**Terminal output**
`$ guake -s 0 -e "lol"
Guake not running, starting it
Loading Gnome schema from: /usr/share/glib-2.0/schemas
Language previously loaded from: /usr/share/locale
Guake Terminal 3.8.6.dev0
VTE 0.66.2
Gtk 3.24.31
created fresh notebook for workspace 0
Spawning new terminal at /home/j
current workspace is 0
can't bind show-focus key
Spawning new terminal at /mnt/storage/wData/user/Downloads/code/musicBot
Spawning new terminal at /mnt/storage/wData/user/Downloads
Spawning new terminal at /mnt/storage/wData/user/Videos
Guake tabs restored from /home/j/.config/guake/session.json
Guake initialized
Traceback (most recent call last):
  File "/usr/bin/guake", line 33, in <module>
    sys.exit(load_entry_point('guake==3.8.6.dev0', 'console_scripts', 'guake')())
  File "/usr/lib/python3.10/site-packages/guake/main.py", line 633, in exec_main
    if not main():
  File "/usr/lib/python3.10/site-packages/guake/main.py", line 552, in main
    remote_object.execute_command(options.command)
AttributeError: 'DbusManager' object has no attribute 'execute_command'`

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.8.6.dev0

Vte Version:		0.66.2

Vte Runtime Version:	0.66.2

--------------------------------------------------
GTK+ Version:		3.24.31

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: xfce

--------------------------------------------------
Display: :0.0

RGBA visual: True

Composited: True

* Monitor: 0 - BNQ DP-4
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		531 x 298 mm²
    * Primary:		True
    * Refresh rate:	144.0 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - AOC DP-0
    * Geometry:		1366 x 768 at 1920, 312
    * Size:		413 x 234 mm²
    * Primary:		False
    * Refresh rate:	59.789 Hz
    * Subpixel layout:	unknown

**Comment by julikaiba** [comment]
Duplicate of #2042
