### ISSUE TITLE
Installation from Source

### ISSUE THREAD

**Issue by anishmittal2020** [Guake/guake#2070]
```bash
	sudo apt-get install --no-install-recommends -y \
		gir1.2-keybinder-3.0 \
		gir1.2-notify-0.7 \
		gir1.2-vte-2.91 \
		gir1.2-wnck-3.0 \
		libkeybinder-3.0-0 \
		libutempter0 \
		python3 \
		python3-cairo \
		python3-dbus \
		python3-gi \
		python3-setuptools-scm \
		python3-pip \
		libgirepository1.0-dev

	make
	sudo make install
```

```bash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-notify-0.7 is already the newest version (0.7.9-1ubuntu2).
gir1.2-wnck-3.0 is already the newest version (3.36.0-1).
libutempter0 is already the newest version (1.1.6-4).
python3 is already the newest version (3.8.2-0ubuntu2).
python3-cairo is already the newest version (1.16.2-2ubuntu2).
python3-dbus is already the newest version (1.2.16-1build1).
python3-gi is already the newest version (3.36.0-1).
gir1.2-keybinder-3.0 is already the newest version (0.3.2-1ubuntu1).
libkeybinder-3.0-0 is already the newest version (0.3.2-1ubuntu1).
python3-setuptools-scm is already the newest version (3.4.3-1ubuntu1).
gir1.2-vte-2.91 is already the newest version (0.60.3-0ubuntu1~20.04).
libgirepository1.0-dev is already the newest version (1.64.1-1~ubuntu20.04.1).
python3-pip is already the newest version (20.0.2-5ubuntu1.6).
0 to upgrade, 0 to newly install, 0 to remove and 3 not to upgrade.
Latest Version: 3.8.5
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
Note: switching to '3.8.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at c48caa7 doc: release notes for 3.8.5
generating desktop files
Generating path.py...
generating po/sv.po
generating po/el.po
generating po/ru.po
generating po/zh_CN.po
generating po/pa.po
generating po/hr.po
generating po/ja.po
generating po/zh_TW.po
generating po/fi.po
generating po/pt_BR.po
generating po/es.po
generating po/cs.po
generating po/fa.po
generating po/pl.po
generating po/id.po
generating po/uk.po
generating po/ko.po
generating po/de.po
generating po/nl.po
generating po/hu.po
generating po/tr.po
generating po/it.po
generating po/nb.po
generating po/fr.po
generating po/ca.po
generating po/gl.po
rm -f /home/nikhil/opt/Library/LibrarySrc/guake/guake/data/gschemas.compiled
glib-compile-schemas --strict /home/nikhil/opt/Library/LibrarySrc/guake/guake/data
# 'make' target, so users can install guake without need to install the 'dev' dependencies
install -dm755                                       "//usr/local/share/applications"
install -Dm644 "/home/nikhil/opt/Library/LibrarySrc/guake/guake/data/guake.desktop"       "//usr/local/share/applications/"
install -Dm644 "/home/nikhil/opt/Library/LibrarySrc/guake/guake/data/guake-prefs.desktop" "//usr/local/share/applications/"
install -dm755                                       "//usr/local/share/metainfo/"
install -Dm644 "/home/nikhil/opt/Library/LibrarySrc/guake/guake/data/guake.desktop.metainfo.xml"  "//usr/local/share/metainfo/"
install -dm755                                 "//usr/local/share/guake/pixmaps"
install -Dm644 "/home/nikhil/opt/Library/LibrarySrc/guake/guake/data"/pixmaps/*.png "//usr/local/share/guake/pixmaps/"
install -Dm644 "/home/nikhil/opt/Library/LibrarySrc/guake/guake/data"/pixmaps/*.svg "//usr/local/share/guake/pixmaps/"
install -dm755                                     "//usr/local/share/pixmaps"
install -Dm644 "/home/nikhil/opt/Library/LibrarySrc/guake/guake/data/pixmaps/guake.png" "//usr/local/share/pixmaps/"
install -dm755                                           "//usr/local/share/guake"
install -Dm644 "/home/nikhil/opt/Library/LibrarySrc/guake/guake/data/autostart-guake.desktop" "//usr/local/share/guake/"
install -dm755                           "//usr/local/share/guake"
install -Dm644 "/home/nikhil/opt/Library/LibrarySrc/guake/guake/data"/*.glade "//usr/local/share/guake/"
install -dm755                                         "//usr/local/share/glib-2.0/schemas"
install -Dm644 "/home/nikhil/opt/Library/LibrarySrc/guake/guake/data/org.guake.gschema.xml" "//usr/local/share/glib-2.0/schemas/"
if [ 1 = 1 ]; then glib-compile-schemas //usr/local/share/glib-2.0/schemas; fi
for f in $(find po -iname "*.mo"); do \
        l="${f%%.*}"; \
        lb=$(basename $l); \
        install -Dm644 "$f" "//usr/local/share/locale/$lb/LC_MESSAGES/guake.mo"; \
done;
# you probably want to execute this target with sudo:
# sudo make install
#############################################################

Installing from source on your system is not recommended.
Please prefer you application package manager (apt, yum, ...)

#############################################################
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    setuptools.setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 447, in __init__
    _Distribution.__init__(self, {
  File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 740, in finalize_options
    ep.load()(self)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 17, in version_keyword
    dist.metadata.version = _get_version(config)
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 150, in _get_version
    version_string = format_version(
  File "/usr/lib/python3/dist-packages/setuptools_scm/version.py", line 307, in format_version
    local_version = local_scheme(version)
TypeError: 'NoneType' object is not callable
make: *** [Makefile:93: install-guake] Error 1
```

**Comment by Davidy22** [comment]
What version of setuptools_scm is on your machine?

**Comment by anishmittal2020** [comment]
```bash
$ pip install setuptools-scm
Requirement already satisfied: setuptools-scm in /home/nikhil/.local/lib/python3.8/site-packages (6.4.2)
Requirement already satisfied: packaging>=20.0 in /home/nikhil/.local/lib/python3.8/site-packages (from setuptools-scm) (21.3)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from setuptools-scm) (45.2.0)
Requirement already satisfied: tomli>=1.0.0 in /home/nikhil/.local/lib/python3.8/site-packages (from setuptools-scm) (2.0.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/nikhil/.local/lib/python3.8/site-packages (from packaging>=20.0->setuptools-scm) (3.0.7)
```

Does this answer's your question?

**Comment by Davidy22** [comment]
Just a hunch, I feel like this shouldn't be different but what about `pip install setuptools_scm` instead of `pip install setuptools-scm`

**Comment by anishmittal2020** [comment]
@Davidy22 

```bash
$ pip install setuptools_scm
Requirement already satisfied: setuptools_scm in /home/nikhil/.local/lib/python3.8/site-packages (6.4.2)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from setuptools_scm) (45.2.0)
Requirement already satisfied: tomli>=1.0.0 in /home/nikhil/.local/lib/python3.8/site-packages (from setuptools_scm) (2.0.1)
Requirement already satisfied: packaging>=20.0 in /home/nikhil/.local/lib/python3.8/site-packages (from setuptools_scm) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/nikhil/.local/lib/python3.8/site-packages (from packaging>=20.0->setuptools_scm) (3.0.7)
```

**Comment by corvus1** [comment]
I just the same in guake 3.8.5
Used to work in 3.8.1

**Comment by anishmittal2020** [comment]
@corvus1 I have choned the complete repository and haven't used the tarball from GitHub Release

**Comment by corvus1** [comment]
I managed to fix my version of this issue by exporting SETUPTOOLS_SCM_PRETEND_VERSION

**Comment by Davidy22** [comment]
Don't have much else off the top of my head, may need to bring this along the chain to setuptools, possibly originates there.

**Comment by dxps** [comment]
@corvus1 Can you be more explicit how you managed to solve it, please?
I'm on Pop!_OS 22.04 and trying to install today's Guake (which should be the just released ver 3.9.0).
Ran:
1. `./scripts/bootstrap-dev-pip.sh run make`
2. `make`
3. `sudo make install`

Last step (3) fails with `LookupError: setuptools-scm was unable to detect version for /tmp/guake.`

**Comment by corvus1** [comment]
> @corvus1 Can you be more explicit how you managed to solve it, please grey_question

Sure, but I doubt it'd be of much help to you, because it's a bit distro-specific.
What I was really doing is I was writing an ebuild for gentoo, and the solution was to export SETUPTOOLS_SCM_PRETEND_VERSION=${PV} environment variable in the ebuild.

**Comment by dxps** [comment]
I think it worked! :heart_eyes:  Thanks! :pray: 

Basically, just doing:
```shell
$ sudo su -
$ cd guake
$ export SETUPTOOLS_SCM_PRETEND_VERSION=3.9.0
$ make install
$
```
And it places the "executable" in `/usr/local/bin`, and since this location exists in `$PATH` before `/usr/bin`, it can coexists with the one installed through the official package manager, so it's all good for now.

**Comment by corvus1** [comment]
I'm glad it helped. :-)

**Comment by corvus1** [comment]
you can usually call something like `make INSTALL_PREFIX=$HOME/apps/whatever install` and it will install wherever it is you want it.

**Comment by dxps** [comment]
Good to know! I'll test that on the other daily distro that I'm using. Thanks again! :+1:

**Comment by dxps** [comment]
Just tested, unfortunately not. Included pretty much everything, hoping it helps the investigation. Thanks!


Preparation:
```shell
/tmp ❯ git clone https://github.com/Guake/guake.git
/tmp ❯ cd guake
guake on  master via 🐍 v2.7.18 ❯ ./scripts/bootstrap-dev-pip.sh run make
Freeze version of pip to ensure build reproductibility
Collecting pip==20.0.2
  Downloading pip-20.0.2-py2.py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 7.5 MB/s eta 0:00:00
Collecting pipenv==2018.11.26
  Downloading pipenv-2018.11.26-py3-none-any.whl (5.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 50.1 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=36.2.1 in /usr/lib/python3/dist-packages (from pipenv==2018.11.26) (59.6.0)
Collecting virtualenv
  Downloading virtualenv-20.14.1-py2.py3-none-any.whl (8.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 48.2 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from pipenv==2018.11.26) (2020.6.20)
Collecting virtualenv-clone>=0.2.5
  Downloading virtualenv_clone-0.5.7-py3-none-any.whl (6.6 kB)
Collecting filelock<4,>=3.2
  Downloading filelock-3.7.1-py3-none-any.whl (10 kB)
Collecting platformdirs<3,>=2
  Downloading platformdirs-2.5.2-py3-none-any.whl (14 kB)
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.4-py2.py3-none-any.whl (461 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 461.2/461.2 KB 31.0 MB/s eta 0:00:00
Requirement already satisfied: six<2,>=1.9.0 in /usr/lib/python3/dist-packages (from virtualenv->pipenv==2018.11.26) (1.16.0)
Installing collected packages: distlib, virtualenv-clone, platformdirs, pip, filelock, virtualenv, pipenv
Successfully installed distlib-0.3.4 filelock-3.7.1 pip-20.0.2 pipenv-2018.11.26 platformdirs-2.5.2 virtualenv-20.14.1 virtualenv-clone-0.5.7
Please ensure your local bin directory is in your path
Linux: export PATH=/home/dxps/.local/bin:/home/dxps/.wasmtime/bin:/home/dxps/.cargo/bin:/home/dxps/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/dxps/apps/bin:/usr/lib/jvm/java-1.17.0-openjdk-amd64/bin:/home/dxps/apps/maven/bin:/home/dxps/apps/node/bin:/home/dxps/apps/vscode/bin:/home/dxps/apps/dbeaver:/home/dxps/.npm-packages/bin:/home/dxps/.npm-packages/bin:/home/dxps/apps/go/bin:/home/dxps/go/bin:/home/dxps/apps/flutter/bin:/home/dxps/.local/bin:/home/dxps/apps/v:/home/dxps/apps/bin:/usr/lib/jvm/java-1.17.0-openjdk-amd64/bin:/home/dxps/apps/maven/bin:/home/dxps/apps/node/bin:/home/dxps/apps/vscode/bin:/home/dxps/apps/dbeaver:/home/dxps/.npm-packages/bin:/home/dxps/.npm-packages/bin:/home/dxps/apps/go/bin:/home/dxps/go/bin:/home/dxps/apps/flutter/bin:/home/dxps/.local/bin:/home/dxps/apps/v
guake on  master via 🐍 v2.7.18 took 5s ❯
```
`make` runs fine. Then trying `sudo make install`:

```shell
guake on  master via 🐍 v2.7.18 ❯ sudo make install
[sudo] password for dxps: 
install -dm755                                       "//usr/local/share/applications"
install -Dm644 "/tmp/guake/guake/data/guake.desktop"       "//usr/local/share/applications/"
install -Dm644 "/tmp/guake/guake/data/guake-prefs.desktop" "//usr/local/share/applications/"
install -dm755                                       "//usr/local/share/metainfo/"
install -Dm644 "/tmp/guake/guake/data/guake.desktop.metainfo.xml"  "//usr/local/share/metainfo/"
install -dm755                                 "//usr/local/share/guake/pixmaps"
install -Dm644 "/tmp/guake/guake/data"/pixmaps/*.png "//usr/local/share/guake/pixmaps/"
install -Dm644 "/tmp/guake/guake/data"/pixmaps/*.svg "//usr/local/share/guake/pixmaps/"
install -dm755                                     "//usr/local/share/pixmaps"
install -Dm644 "/tmp/guake/guake/data/pixmaps/guake.png" "//usr/local/share/pixmaps/"
install -dm755                                           "//usr/local/share/guake"
install -Dm644 "/tmp/guake/guake/data/autostart-guake.desktop" "//usr/local/share/guake/"
install -dm755                           "//usr/local/share/guake"
install -Dm644 "/tmp/guake/guake/data"/*.glade "//usr/local/share/guake/"
install -dm755                                         "//usr/local/share/glib-2.0/schemas"
install -Dm644 "/tmp/guake/guake/data/org.guake.gschema.xml" "//usr/local/share/glib-2.0/schemas/"
if [ 1 = 1 ]; then glib-compile-schemas //usr/local/share/glib-2.0/schemas; fi
for f in $(find po -iname "*.mo"); do \
	l="${f%%.*}"; \
	lb=$(basename $l); \
	install -Dm644 "$f" "//usr/local/share/locale/$lb/LC_MESSAGES/guake.mo"; \
done;
# you probably want to execute this target with sudo:
# sudo make install
#############################################################

Installing from source on your system is not recommended.
Please prefer you application package manager (apt, yum, ...)

#############################################################
Processing /tmp/guake
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 5, in <module>
          setuptools.setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 459, in __init__
          _Distribution.__init__(
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 837, in finalize_options
          ep(self)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 858, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 75, in version_keyword
          _assign_version(dist, config)
        File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 51, in _assign_version
          _version_missing(config)
        File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 106, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /tmp/guake.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
-e setup.py install failed, you may need to run "sudo git config --global --add safe.directory '*'"
Could not parse file "/usr/share/applications/guake.desktop": No such file or directory
guake on  master via 🐍 v2.7.18 took 10s ❯
```

**Comment by dxps** [comment]
But if I'm doing as @corvus1 nicely pointed before, it works. That means running:
`sudo make SETUPTOOLS_SCM_PRETEND_VERSION=3.9.0 install`

**Comment by Davidy22** [comment]
Oh, wait, I missed the v2.7.18 earlier. I think I know where the issue is now. Could try write a little something to make this run differently if we're still on python 2.

**Comment by Davidy22** [comment]
I pushed f8f968a7850644fdd93069eed0ee35da8463afec which added one line to check for python 2 and insert the environment variable,  The above error looks like something introduced by a recent git update, you might notice a message inserted in the output near the end that might be red on your terminal, advising to run `sudo git config --global --add safe.directory '*'` or replace the * with just the path to your guake dir if you want to follow the letter of the git update and do this per repo

**Comment by dxps** [comment]
> is it trying to run the py3 version of setuptools on py2.7?

@corvus1  How should I find the answer? Sorry, not a Python fan :relaxed: 

@Davidy22 Ran that `git config` as well, fetched the latest git changes, and :partying_face: !!!
It looks all went great and now I have `3.9.1.dev9` version running. How cool is that!

Thanks for the help! :pray:
