### ISSUE TITLE
"AssertionError: Application is already running" closing terminal with xonsh

### ISSUE THREAD

**Issue by johny65** [Guake/guake#2086]
**Describe the bug**

When running [xonsh](https://xon.sh), closing a terminal (when you divide the tab in multiple terminals) throws the following exception and the terminal isn't closed, it gets in the failback shell:

```
[20:47:06] $ Traceback (most recent call last):
  File "/home/johny/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 21649, in main
    sys.exit(main_xonsh(args))
  File "/home/johny/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 21693, in main_xonsh
    shell.shell.cmdloop()
  File "/home/johny/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/ptk_shell/shell.py", line 399, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/johny/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/ptk_shell/shell.py", line 368, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/home/johny/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1034, in prompt
    return self.app.run(
  File "/home/johny/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 936, in run
    return loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/johny/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 663, in run_async
    assert not self._is_running, "Application is already running."
AssertionError: Application is already running.
Xonsh encountered an issue during launch
Failback to /bin/bash
```

Notes: I have xonsh installed though `pipx` in Ubuntu 22.04.

**Expected behavior**

To close the terminal without problems.

**Actual behavior**

It throws the mentioned exception.

**To Reproduce**

- Start Guake.
- $ xonsh
- xonsh prompt >
- Press keybinding to close terminal.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.8.5

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.33

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: openbox

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: False

* Monitor: 0 - SAM HDMI-1
    * Geometry:		1920 x 1080 at 1366, 0
    * Size:		477 x 268 mm²
    * Primary:		True
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - LGD LVDS-1
    * Geometry:		1366 x 768 at 0, 0
    * Size:		344 x 194 mm²
    * Primary:		False
    * Refresh rate:	59.991 Hz
    * Subpixel layout:	horizontal-rgb

**Comment by Davidy22** [comment]
The traceback seems to be entirely calls inside xonsh, this should probably be reported on the xonsh side instead of here.
