### ISSUE TITLE
Guake missing copy/paste option on right-click

### ISSUE THREAD

**Issue by johnny-mac** [Guake/guake#2092]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

**Describe the bug**
there is no copy/paste option when right-clicking

**Expected behavior**
there should be an option to copy/paste

**Actual behavior**
guake
Guake not running, starting it
Loading Gnome schema from: /usr/share/glib-2.0/schemas
Language previously loaded from: /usr/share/locale
Guake Terminal 3.8.6.dev0
VTE 0.68.0
Gtk 3.24.34
created fresh notebook for workspace 0
Spawning new terminal at /home/kzv
current workspace is 0
can't bind show-focus key
Spawning new terminal at /home/kzv/Transfers/backupfeb
Spawning new terminal at /home/kzv/Videos
Guake tabs restored from /home/kzv/.config/guake/session.json
Guake initialized
Current link under cursor: None
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/guake/boxes.py", line 523, in on_button_press
    menu = mk_terminal_context_menu(
  File "/usr/lib/python3.10/site-packages/guake/menus.py", line 94, in mk_terminal_context_menu
    mi = Gtk.MenuItem(_("Split ���"))
UnicodeDecodeError: 'locale' codec can't decode byte 0xe2 in position 6: decoding error

What you actually get.

**To Reproduce**
I do not know if this is reproducable or not, its only doing this to me on one computer, the others work fine. Is there a dependency missing perhaps?

Provide the steps to reproduce the behavior

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

guake --support
<details><summary>$ guake --support</summary>

Guake Version:		3.8.6.dev0

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.34

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: LXDE

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - HWP DVI-D-0
    * Geometry:		1920 x 1200 at 0, 0
    * Size:		518 x 324 mm��
    * Primary:		True
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown

**Comment by johnny-mac** [comment]
Both Guake in the [Community] (ArchLinux) repo and Guake from the AUR do this. I don't know what I am missing. I would be a very happy user to figure this out!

**Comment by johnny-mac** [comment]
figured it out, locale.conf was empty. My bad!
