### ISSUE TITLE
Unable to install guake on Ubuntu 22.04

### ISSUE THREAD

**Issue by serpro69** [Guake/guake#2100]
Tried installing guake via pip and pipx, none of them worked on a fresh Ubuntu 22.04

Followed the instructions @ https://guake.readthedocs.io/en/latest/user/installing.html#install-from-pypi 

**Describe the bug**

exceptions are thrown after installing via `pip` or `pipx`

**Expected behavior**

running `guake` should launch the temrinal

**Actual behavior**

Installing via `pip` with `--user` flag throws the following exception:

```
Guake not running, starting it
Loading Gnome schema from: /home/sergio/.local/lib/python3.10/site-packages/guake/data
Unable to load the GLib schema, try to compile it
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sergio/.local/lib/python3.10/site-packages/guake/main.py", line 473, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sergio/.local/lib/python3.10/site-packages/guake/guake_app.py", line 111, in __init__
    schema_source = load_schema()
  File "/home/sergio/.local/lib/python3.10/site-packages/guake/guake_app.py", line 106, in load_schema
    return Gio.SettingsSchemaSource.new_from_directory(
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/sergio/.local/lib/python3.10/site-packages/guake/data/gschemas.compiled”: open() failed: No such file or directory (4)
Compiling schema: /home/sergio/.local/lib/python3.10/site-packages/guake/data
Error opening directory “/home/sergio/.local/lib/python3.10/site-packages/guake/data”: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sergio/.local/lib/python3.10/site-packages/guake/main.py", line 473, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sergio/.local/lib/python3.10/site-packages/guake/guake_app.py", line 111, in __init__
    schema_source = load_schema()
  File "/home/sergio/.local/lib/python3.10/site-packages/guake/guake_app.py", line 106, in load_schema
    return Gio.SettingsSchemaSource.new_from_directory(
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/sergio/.local/lib/python3.10/site-packages/guake/data/gschemas.compiled”: open() failed: No such file or directory (4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sergio/.local/bin/guake", line 8, in <module>
    sys.exit(exec_main())
  File "/home/sergio/.local/lib/python3.10/site-packages/guake/main.py", line 648, in exec_main
    if not main():
  File "/home/sergio/.local/lib/python3.10/site-packages/guake/main.py", line 489, in main
    instance = Guake()
  File "/home/sergio/.local/lib/python3.10/site-packages/guake/guake_app.py", line 114, in __init__
    try_to_compile_glib_schemas()
  File "/home/sergio/.local/lib/python3.10/site-packages/guake/paths.py", line 96, in try_to_compile_glib_schemas
    subprocess.check_call(["glib-compile-schemas", "--strict", SCHEMA_DIR])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['glib-compile-schemas', '--strict', '/home/sergio/.local/lib/python3.10/site-packages/guake/data']' returned non-zero exit status 1.
```

Installing via `pipx` : 

```
Traceback (most recent call last):
  File "/home/sergio/.local/bin/guake", line 5, in <module>
    from guake.main import exec_main
  File "/home/sergio/.local/pipx/venvs/guake/lib/python3.10/site-packages/guake/main.py", line 54, in <module>
    from guake.support import print_support
  File "/home/sergio/.local/pipx/venvs/guake/lib/python3.10/site-packages/guake/support.py", line 5, in <module>
    import gi
**ModuleNotFoundError: No module named 'gi'**
```

**To Reproduce**

```
sudo apt install gir1.2-keybinder-3.0 gir1.2-notify-0.7 gir1.2-vte-2.91 libkeybinder-3.0-0 libutempter0 python3-setuptools python3-cairo python3-dbus python3-gi python3-pbr python3-pip python3 gir1.2-wnck-3.0

# via pip
pip install --user guake
guake # error is thrown

# or via pipx
python3 -m pip install --user pipx
sudo apt install python3.10-venv
pipx install guake
guake # error is thrown
```

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

**Comment by serpro69** [comment]
I've found that the latest working version for me is 3.7.0. After that, there are a couple of 3.8.2.0rc* versions, and the next release is 3.8.5 which is broken.

```
$ pip install --user 'guake==3.7.0'
Collecting guake==3.7.0
  Using cached guake-3.7.0-py2.py3-none-any.whl (1.2 MB)
Requirement already satisfied: pbr in ./.local/lib/python3.10/site-packages (from guake==3.7.0) (5.9.0)
Installing collected packages: guake
Successfully installed guake-3.7.0

$ guake
Guake not running, starting it
Loading Gnome schema from: /home/sergio/.local/lib/python3.10/site-packages/guake/data
Language previously loaded from: /home/sergio/.local/lib/python3.10/site-packages/guake/po
Guake Terminal 3.7.0
VTE 0.68.0
Gtk 3.24.33
created fresh notebook for workspace 0
Spawning new terminal at /home/sergio

(guake:36817): VTE-WARNING **: 14:48:28.921: (../src/vtepty.cc:667):bool _vte_pty_spawn_sync(VtePty*, const char*, const char* const*, const char* const*, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, GPid*, int, GCancellable*, GError**): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
current workspace is 0
can't bind show-focus key
Spawning new terminal at /home/sergio

(guake:36817): VTE-WARNING **: 14:48:28.993: (../src/vtepty.cc:667):bool _vte_pty_spawn_sync(VtePty*, const char*, const char* const*, const char* const*, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, GPid*, int, GCancellable*, GError**): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
Spawning new terminal at /home/sergio

(guake:36817): VTE-WARNING **: 14:48:29.003: (../src/vtepty.cc:667):bool _vte_pty_spawn_sync(VtePty*, const char*, const char* const*, const char* const*, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, GPid*, int, GCancellable*, GError**): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
Guake tabs restored from /home/sergio/.config/guake/session.json
Guake initialized
Guake tabs saved to /home/sergio/.config/guake/session.json

```

**Comment by matheo** [comment]
I just tried to `pip install --user 'guake==3.7.0'` in my recently upgraded Ubuntu 22.04 and `$ guake` throws this output:
```
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
ERROR:dbus.proxies:Introspect error on :1.87:/org/guake3/RemoteControl: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/bin/guake", line 33, in <module>
    sys.exit(load_entry_point('guake==3.8.5', 'console_scripts', 'guake')())
  File "/home/matheo/.local/lib/python3.10/site-packages/guake/main.py", line 614, in exec_main
    if not main():
  File "/home/matheo/.local/lib/python3.10/site-packages/guake/main.py", line 591, in main
    remote_object.show_hide()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
