### ISSUE TITLE
Guake will not run on Ubuntu 22.04 after general package upgrade

### ISSUE THREAD

**Issue by StewAlexander-com** [Guake/guake#2123]
Guake fails with this output:
```
Stew Alexander, [8/18/2022 9:58 AM]
support@Network-VM:~$ guake
Guake not running, starting it
Loading Gnome schema from: /home/support/.local/lib/python3.10/site-packages/guake/data
Unable to load the GLib schema, try to compile it
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/lib/python3.10/site-packages/guake/main.py", line 473, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in init
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 111, in init
    schema_source = load_schema()
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 106, in load_schema
    return Gio.SettingsSchemaSource.new_from_directory(
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/support/.local/lib/python3.10/site-packages/guake/data/gschemas.compiled”: open() failed: No such file or directory (4)
Compiling schema: /home/support/.local/lib/python3.10/site-packages/guake/data
Error opening directory “/home/support/.local/lib/python3.10/site-packages/guake/data”: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Stew Alexander, [8/18/2022 9:58 AM]
Traceback (most recent call last):
  File "/home/support/.local/lib/python3.10/site-packages/guake/main.py", line 473, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in init
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 111, in init
    schema_source = load_schema()
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 106, in load_schema
    return Gio.SettingsSchemaSource.new_from_directory(
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/support/.local/lib/python3.10/site-packages/guake/data/gschemas.compiled”: open() failed: No such file or directory (4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/bin/guake", line 8, in <module>
    sys.exit(exec_main())
  File "/home/support/.local/lib/python3.10/site-packages/guake/main.py", line 648, in exec_main
    if not main():
  File "/home/support/.local/lib/python3.10/site-packages/guake/main.py", line 489, in main
    instance = Guake()
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 114, in init
    try_to_compile_glib_schemas()
  File "/home/support/.local/lib/python3.10/site-packages/guake/paths.py", line 96, in try_to_compile_glib_schemas
    subprocess.check_call(["glib-compile-schemas", "--strict", SCHEMA_DIR])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['glib-compile-schemas', '--strict', '/home/support/.local/lib/python3.10/site-packages/guake/data']' returned non-zero exit status 1.
```

**Comment by StewAlexander-com** [comment]
Python vesion 3.10.4 installed

**Comment by nmay231** [comment]
@StewAlexander-com How is it installed, pipx install, built from source? And what is the output of `guake --support`? (assuming it doesn't error as well).

**Comment by StewAlexander-com** [comment]
Installed Guake via apt-get 

```
support@Network-VM:~$ guake --support
<details><summary>$ guake --support</summary>

Guake Version:    3.9.0

Vte Version:    0.68.0

Vte Runtime Version:  0.68.0

--------------------------------------------------
GTK+ Version:    3.24.33

GDK Backend:    <GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND0
    * Geometry:    1856 x 1392 at 0, 0
    * Size:    491 x 368 mm²
    * Primary:    True
    * Refresh rate:  59.934000000000005 Hz
    * Subpixel layout:  unknown
support@Network-VM:~$
```

**Comment by nmay231** [comment]
Just to cover all the bases, make sure you have all of the system packages installed [listed in the docs](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-pypi).

That error sometimes happens when you have multiple versions of guake installed. Double-check that guake is in `/usr/bin` or `/usr/local/bin`: `which guake`. If it's not, uninstall any other versions you might have tried installing (e.g. from pip or from a source build).

I assume you're using a ppa to install guake? If those actions don't work, you can try switching from the ppa to the system version of guake (`3.9.0` => `3.8.5`).
```bash
sudo apt uninstall guake
sudo add-apt-repository --remove ppa:linuxuprising/guake
sudo apt update
sudo apt install guake
```

**Comment by LeDuble** [comment]
Ive received the same error message today.

Ive got all dependencies and required packages. It just stopped working all of sudden.

I have uninstalled guake and re-installed with ppa method. But now it says guake package isnt installed

**Comment by nmay231** [comment]
@LeDuble It's unlikely that it "just stopped working". Do you have automatic updates enabled?

Try installing all the packages listed in the docs just in case there's a new one or something. Then **Remove** the ppa by following the instructions listed in my comment above. I'm on Ubuntu 22.04.1 and the latest version of guake from the regular system package index is 3.8.5-1 (`apt info guake`) and it starts fine for me. (It has other bugs, but that's not the issue right now).

**Comment by StewAlexander-com** [comment]
Let me try the suggestions and report back, thanks

**Comment by StewAlexander-com** [comment]
Uninstalled guake, removed the ppa repo, and installed the earlier version similar traceback errors

---
```
support@Network-VM:~$ sudo add-apt-repository --remove ppa:linuxuprising/guake
Repository: 'deb https://ppa.launchpadcontent.net/linuxuprising/guake/ubuntu/ jammy main'
Description:
Latest Guake PPA

PPA release announcement on Linux Uprising: https://www.linuxuprising.com/2019/05/new-guake-drop-down-terminal-ppa-ubuntu.html
More info: https://launchpad.net/~linuxuprising/+archive/ubuntu/guake
Removing repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Disabling deb entry in /etc/apt/sources.list.d/linuxuprising-ubuntu-guake-jammy.list
Removing disabled deb entry from /etc/apt/sources.list.d/linuxuprising-ubuntu-guake-jammy.list
Removing disabled deb-src entry from /etc/apt/sources.list.d/linuxuprising-ubuntu-guake-jammy.list
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease           
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease                             
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease                                
Hit:5 http://archive.canonical.com/ubuntu jammy InRelease                                       
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease             
Hit:6 https://packagecloud.io/AtomEditor/atom/any any InRelease
Reading package lists... Done                                 
W: https://packagecloud.io/AtomEditor/atom/any/dists/any/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
support@Network-VM:~$ sudo apt update
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy InRelease                                       
Hit:3 http://archive.canonical.com/ubuntu jammy InRelease                                       
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease                               
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease                             
Hit:6 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease                    
Hit:7 https://packagecloud.io/AtomEditor/atom/any any InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
14 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: https://packagecloud.io/AtomEditor/atom/any/dists/any/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
support@Network-VM:~$ sudo apt install guake
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  systemd-hwe-hwdb
Use 'sudo apt autoremove' to remove it.
Suggested packages:
  numix-gtk-theme
The following NEW packages will be installed:
  guake
0 upgraded, 1 newly installed, 0 to remove and 14 not upgraded.
Need to get 380 kB of archives.
After this operation, 1,798 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 guake all 3.8.5-1 [380 kB]
Fetched 380 kB in 0s (1,337 kB/s)
Selecting previously unselected package guake.
(Reading database ... 220371 files and directories currently installed.)
Preparing to unpack .../archives/guake_3.8.5-1_all.deb ...
Unpacking guake (3.8.5-1) ...
Setting up guake (3.8.5-1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for libglib2.0-0:amd64 (2.72.1-1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
support@Network-VM:~$ guake
Guake not running, starting it
Loading Gnome schema from: /home/support/.local/lib/python3.10/site-packages/guake/data
Unable to load the GLib schema, try to compile it
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/lib/python3.10/site-packages/guake/main.py", line 473, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 111, in __init__
    schema_source = load_schema()
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 106, in load_schema
    return Gio.SettingsSchemaSource.new_from_directory(
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/support/.local/lib/python3.10/site-packages/guake/data/gschemas.compiled”: open() failed: No such file or directory (4)
Compiling schema: /home/support/.local/lib/python3.10/site-packages/guake/data
Error opening directory “/home/support/.local/lib/python3.10/site-packages/guake/data”: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/lib/python3.10/site-packages/guake/main.py", line 473, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 111, in __init__
    schema_source = load_schema()
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 106, in load_schema
    return Gio.SettingsSchemaSource.new_from_directory(
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/support/.local/lib/python3.10/site-packages/guake/data/gschemas.compiled”: open() failed: No such file or directory (4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/bin/guake", line 8, in <module>
    sys.exit(exec_main())
  File "/home/support/.local/lib/python3.10/site-packages/guake/main.py", line 648, in exec_main
    if not main():
  File "/home/support/.local/lib/python3.10/site-packages/guake/main.py", line 489, in main
    instance = Guake()
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 114, in __init__
    try_to_compile_glib_schemas()
  File "/home/support/.local/lib/python3.10/site-packages/guake/paths.py", line 96, in try_to_compile_glib_schemas
    subprocess.check_call(["glib-compile-schemas", "--strict", SCHEMA_DIR])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['glib-compile-schemas', '--strict', '/home/support/.local/lib/python3.10/site-packages/guake/data']' returned non-zero exit status 1.
support@Network-VM:~$ 
```

**Comment by StewAlexander-com** [comment]
Looks perhaps to be maybe a *****python***** dependency issue?

**Comment by StewAlexander-com** [comment]
**Python Version**
---
```
support@Network-VM:~$ python3 --version
Python 3.10.6
```

**Comment by nmay231** [comment]
@StewAlexander-com Going with the system version worked for me just recently, which is why I'm confused. Double-check you don't have the pip version installed (`pip3 uninstall guake` and `pip uninstall guake` for good measure).

Also, what's the output of `which guake`, `which python` and `head $(which guake)`?

**Comment by StewAlexander-com** [comment]
using ```pip3 uninstall guake``` actually deleted guake, that was likely my culprit...

Re-installing via ```apt``` went without issue

Yep that did it!!

Thanks @nmay231 

So, bigger issue is why the latest guake release doesn't like the latest version of Ubuntu?

**Comment by StewAlexander-com** [comment]
Hmm toggling visibility via key command (like _```Shift-F11```_) doesn't appear to work on the release available via ```apt```, does it work for anyone else? If not I'll open a different bug

**Comment by nmay231** [comment]
@StewAlexander-com  I don't think it is the version that's causing the issue, but rather the install location and where the data is expected to be found (it can't find the data folder `python3.10/site-packages/guake/data/gschemas.compiled`). You can track #1971 for when that issue will be resolved.

As for the toggle issue, that is due to Wayland blocking certain or not using global keybinds (I forget which). I can't find the issue right now, but the solution is to create a system-wide keybind that calls `guake-toggle` or `guake -t` (both work).

**Comment by StewAlexander-com** [comment]
@nmay231 - interesting info

For those not in the know, you can find info about [Ubuntu Keybindings here][(https://wiki.ubuntu.com/Keybindings)

Closing this as it looks like the other issues are addresses in other open tickets, thanks to everyone for their help

**Comment by kurokirasama** [comment]
> pip uninstall guake

uninstalling the pip versions worked for me

**Comment by carlosromel** [comment]
Hi.

Using PPA's last version (3.9.0-1), works on Ubuntu 22.04.1.

```
sudo apt remove guake --purge
sudo add-apt-repository ppa:linuxuprising/guake
sudo apt update
sudo apt install guake
```

After some time...

```
$ guake --version
Guake Terminal: 3.9.0
VTE: 0.68.0
VTE runtime: 0.68.0
Gtk: 3.24.33
```

I hope it works for you too.

**Comment by sasikiranE** [comment]
> Hi.
> 
> Using PPA's last version (3.9.0-1), works on Ubuntu 22.04.1.
> 
> ```
> sudo apt remove guake --purge
> sudo add-apt-repository ppa:linuxuprising/guake
> sudo apt update
> sudo apt install guake
> ```
> 
> After some time...
> 
> ```
> $ guake --version
> Guake Terminal: 3.9.0
> VTE: 0.68.0
> VTE runtime: 0.68.0
> Gtk: 3.24.33
> ```
> 
> I hope it works for you too.

This actually worked for me. Thank You
