### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by aylusltd** [Guake/guake#2130]
**Describe the bug**
<img width="823" alt="image" src="https://user-images.githubusercontent.com/965390/192421453-9f479e9d-a19b-45bd-a456-6e951d4cdade.png">

This page (and presumably the whole build) is broken https://guake.readthedocs.io/en/latest/user/cli.html

**Expected behavior**

Program should run

**Actual behavior**

Program does not run...

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/latest/bin/guake", line 33, in <module>
    sys.exit(load_entry_point('guake==3.9.1.dev16', 'console_scripts', 'guake')())
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/latest/bin/guake", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/latest/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/latest/lib/python3.7/site-packages/guake-3.9.1.dev16-py3.7.egg/guake/main.py", line 54, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/guake/envs/latest/lib/python3.7/site-packages/guake-3.9.1.dev16-py3.7.egg/guake/support.py", line 5, in <module>
ModuleNotFoundError: No module named 'gi'

```

**To Reproduce**
Go to url above.

**Comment by mullenkamp** [comment]
This is probably related to #1971 
The pip install is quite broken.

**Comment by novaTopFlex** [comment]
The lack of a module named `gi` is probably not an issue that is the most closely related to the Guake Terminal but rather to a graphical toolkit known as GTK (for 4.0; formerly Gtk+ for versions 2.0 and 3.0) and Python interface, `PyGObject`. For installation:

    pip install PyGObject

This Python package should install two (2) modules: `gi` and `pygtkcompat`.
