### ISSUE TITLE
Guake not installing on Ubuntu 22.0.4.1 LTS - getting traceback errors

### ISSUE THREAD

**Issue by StewAlexander-com** [Guake/guake#2131]
**Distribution Release**
---
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
```

**Python Release**
----
```
support@Network-VM:~$ python3 --version
Python 3.10.6
```

**Traceback errors**
---
```
Guake not running, starting it
Loading Gnome schema from: /home/support/.local/lib/python3.10/site-packages/guake/data
Unable to load the GLib schema, try to compile it
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/lib/python3.10/site-packages/guake/main.py", line 473, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 111, in __init__
    schema_source = load_schema()
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 106, in load_schema
    return Gio.SettingsSchemaSource.new_from_directory(
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/support/.local/lib/python3.10/site-packages/guake/data/gschemas.compiled”: open() failed: No such file or directory (4)
Compiling schema: /home/support/.local/lib/python3.10/site-packages/guake/data
Error opening directory “/home/support/.local/lib/python3.10/site-packages/guake/data”: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/lib/python3.10/site-packages/guake/main.py", line 473, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 111, in __init__
    schema_source = load_schema()
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 106, in load_schema
    return Gio.SettingsSchemaSource.new_from_directory(
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/home/support/.local/lib/python3.10/site-packages/guake/data/gschemas.compiled”: open() failed: No such file or directory (4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/support/.local/bin/guake", line 8, in <module>
    sys.exit(exec_main())
  File "/home/support/.local/lib/python3.10/site-packages/guake/main.py", line 648, in exec_main
    if not main():
  File "/home/support/.local/lib/python3.10/site-packages/guake/main.py", line 489, in main
    instance = Guake()
  File "/home/support/.local/lib/python3.10/site-packages/guake/guake_app.py", line 114, in __init__
    try_to_compile_glib_schemas()
  File "/home/support/.local/lib/python3.10/site-packages/guake/paths.py", line 96, in try_to_compile_glib_schemas
    subprocess.check_call(["glib-compile-schemas", "--strict", SCHEMA_DIR])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['glib-compile-schemas', '--strict', '/home/support/.local/lib/python3.10/site-packages/guake/data']' returned non-zero exit status 1.
```

**Comment by StewAlexander-com** [comment]
Looks as if it might have a python dependency issue?

**Comment by StewAlexander-com** [comment]
Duplicate of ticket  #2123, closing
