### ISSUE TITLE
Guake fails to start.

### ISSUE THREAD

**Issue by davidctinescu** [Guake/guake#2237]
**Describe the bug**

Guake fails to start.

**Expected behavior**

Guake starts normally.

**Actual behavior**

Guake exits with an error:
```
Guake not running, starting it
Loading Gnome schema from: /home/user/.local/lib/python3.10/site-packages/guake/data
Language previously loaded from: /home/user/.local/lib/python3.10/site-packages/guake/po
Guake Terminal 3.10
VTE 0.68.0
Gtk 3.24.33
created fresh notebook for workspace 0
Spawning new terminal at /home/user
current workspace is 0
can't bind show-focus key
Guake initialized
Calling startup script: zsh -c "fortune | cowsay"
Traceback (most recent call last):
  File "/home/user/.local/bin/guake", line 8, in <module>
    sys.exit(exec_main())
  File "/home/user/.local/lib/python3.10/site-packages/guake/main.py", line 664, in exec_main
    if not main():
  File "/home/user/.local/lib/python3.10/site-packages/guake/main.py", line 646, in main
    pid = subprocess.Popen(  # pylint: disable=consider-using-with
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'zsh -c "fortune | cowsay"'
```

**To Reproduce**

Running Guake normally

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.10

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.33

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: xfce

--------------------------------------------------
Display: :0.0

RGBA visual: True

Composited: True

* Monitor: 0 - PHL HDMI-1-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		598 x 336 mm²
    * Primary:		True
    * Refresh rate:	74.97200000000001 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - NCP eDP-1-1
    * Geometry:		1920 x 1080 at 1920, 0
    * Size:		344 x 194 mm²
    * Primary:		False
    * Refresh rate:	144.0 Hz
    * Subpixel layout:	unknown

**Comment by davidctinescu** [comment]
Had to run:
`guake --restore-preferences pref.txt`
Then modify the file to remove `startup-script='zsh -c "fortune | cowsay"'` and `[hooks]
show=''zsh -c "fortune | cowsay""`
