### ISSUE TITLE
guake on OpenSuse Tumbleweed (KDE) - python stack traces

### ISSUE THREAD

**Issue by sygibson** [Guake/guake#2254]
**Describe the bug**
I installed Guake on OpenSuse Tumbleweed (latest 20240802).  It is KDE.  I installed with "(sudo zypper install guake").  On starting Guake, a whole lotta python stack traces happen.  I realize that Guake is a Gnome app by default, and this is a KDE environment.  However, I would expect the appropriate compatibility libraries have been installed.  

On starting Guake, I receive the following:

```
shane@opal:~$ guake
Guake not running, starting it
Loading Gnome schema from: /usr/share/glib-2.0/schemas
Schema from old guake version detected, regenerating schema
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/guake/main.py", line 479, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files
Compiling schema: /usr/share/glib-2.0/schemas
Failed to create file “/usr/share/glib-2.0/schemas/gschemas.compiled.U8WXR2”: Permission denied
Schema in non user-editable location, attempting to continue
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/guake/main.py", line 479, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/guake/guake_app.py", line 127, in __init__
    try_to_compile_glib_schemas()
  File "/usr/lib/python3.11/site-packages/guake/paths.py", line 96, in try_to_compile_glib_schemas
    subprocess.check_call(["glib-compile-schemas", "--strict", SCHEMA_DIR])
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['glib-compile-schemas', '--strict', '/usr/share/glib-2.0/schemas']' returned non-zero exit status 1.
Loading Gnome schema from: /usr/share/glib-2.0/schemas
Language previously loaded from: /usr/share/locale
Guake Terminal 3.10
VTE 0.76.3
Gtk 3.24.43
created fresh notebook for workspace 0
Spawning new terminal at /home/shane
current workspace is 0
can't bind show-focus key
Cannot find session.json file
Guake initialized
```

**Expected behavior**

I would expect Guake to start up cleanly without python stack traces.

**Actual behavior**

A whole bunch of python stack traces as above.

**To Reproduce**

OpenSuse Tumbleweed updated to 20240802 version.
`sudo zypper install guake`
`guake`

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:          3.10

Vte Version:            0.76.3

Vte Runtime Version:    0.76.3

--------------------------------------------------
GTK+ Version:           3.24.43

GDK Backend:            <GdkX11.X11Display

--------------------------------------------------
Desktop Session: plasma6

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - DEL DP-5
    * Geometry:         1920 x 1080 at 1920, 0
    * Size:             600 x 340 mm²
    * Primary:          True
    * Refresh rate:     50.0 Hz
    * Subpixel layout:  unknown
* Monitor: 1 - BOE eDP-2
    * Geometry:         1920 x 1200 at 1401, 1080
    * Size:             345 x 215 mm²
    * Primary:          False
    * Refresh rate:     165.0 Hz
    * Subpixel layout:  unknown
* Monitor: 2 - DEL DP-4
    * Geometry:         1920 x 1080 at 0, 0
    * Size:             600 x 340 mm²
    * Primary:          False
    * Refresh rate:     59.962 Hz
    * Subpixel layout:  unknown

**Comment by Davidy22** [comment]
I suspect it might be a packaging issue, what does `glib-compile-schemas --version` show for you?
