### ISSUE TITLE
Appears to be incompatible with GNOME 47

### ISSUE THREAD

**Issue by iconoclasthero** [Guake/guake#2255]
**Describe the bug**
Appears to be incompatible with GNOME 47.  Pressing `toggle visibility` does various things.  Sometimes it causes the window to blink on, sometimes, if you hit it enough, it causes it to STAY ON!!!  When it's on, sometimes it causes guake to blink off, sometimes it causes guake to stay off.

Also it appears on the wrong window from time to time, refuses to show up on one of my monitors at all....  not really showing up when and where it's supposed to and if it does, it doesn't stay there when told to do so.  It's like a poorly trained dog.

**Expected behavior**
Normal `toggle visibility` function.

**Actual behavior**
Pressing `toggle visibility` does various things.  Sometimes it causes the window to blink on, sometimes, if you hit it enough, it causes it to STAY ON!!!  When it's on, sometimes it causes guake to blink off, sometimes it causes guake to stay off.

Also it appears on the wrong window from time to time, refuses to show up on one of my monitors at all....  not really showing up when and where it's supposed to and if it does, it doesn't stay there when told to do so.  It's like a poorly trained dog.

**To Reproduce**
`toggle visibility` in GNOME 47

**NB**
It _appears_ that using `$ guake-toggle` from the cli works properly.

-------------------------------------------------------------------------------

$ guake --support</summary>

Guake Version:		3.10

Vte Version:		0.77.91

Vte Runtime Version:	0.77.91

--------------------------------------------------
GTK+ Version:		3.24.43

GDK Backend:		None

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/guake", line 33, in <module>
    sys.exit(load_entry_point('guake==3.10', 'console_scripts', 'guake')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/guake/main.py", line 664, in exec_main
    if not main():
           ^^^^^^
  File "/usr/lib/python3/dist-packages/guake/main.py", line 462, in main
    print_support()
  File "/usr/lib/python3/dist-packages/guake/support.py", line 94, in print_support
    get_display()
  File "/usr/lib/python3/dist-packages/guake/support.py", line 86, in get_display
    populate_display(display)
  File "/usr/lib/python3/dist-packages/guake/support.py", line 22, in populate_display
    screen = display.get_default_screen()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_default_screen'

--------------------------------------------------

--------------------------------------------------
OS: Rhino Linux 2024.2~RC (server) x86_64 
Kernel: Linux 6.10.4-061004-generic 
Shell: bash 5.2.21 
Resolution: 1920x1080, 2560x1440, 1920x1080, 2560x1440 
DE: GNOME 47.beta (Wayland) 
DE: GNOME Shell 47.beta 
WM: Mutter 
Terminal: guake

**Comment by iconoclasthero** [comment]
I managed to get back to gnome 46 on X and the problems went away, literally everything else being equal...

```
OS: Rhino Linux 2024.2~RC (server) x86_64 
Kernel: Linux 6.10.4-061004-generic 
Shell: bash 5.2.21 
Resolution: 2560x1440 @ 59.95Hz, 1920x1080 @ 60.00Hz, 1920x1080 @ 60.00Hz, 2560x1440 @ 59.95Hz 
DE: GNOME 46.0 
DE: GNOME Shell 46.0 
WM: Mutter 
Terminal: guake 

$ echo $XDG_SESSION_TYPE 
x11
```

**Comment by johnheenan** [comment]
Here is a workaround:

Remove F12 as key to 'Toggle Guake visibilty' in Guake Properties.
Add F12 as 'Custom Shortcut' to command 'guake-toggle' in Gnome, Settings, Keyboard, View and Customize Shortcuts.

**Comment by iconoclasthero** [comment]
As a workaround I downgraded GNOME back ca. 46.0 or whatever was available
when the Oracular repo was initiated on the machine I installed GNOME on
right after 46.x was removed from the Oracular repo.
On my other machine I apt-mark held enough to keep 46 from being upgraded
to 47...

So for now, this is an FYI that you may have some issues with 47, but I can
remap F12 when I do upgrade to 47.  Had 46 not taken care of it, that
would, in fact, have been my next step.

**Comment by effectfully** [comment]
> Here is a workaround:
>
> Remove F12 as key to 'Toggle Guake visibilty' in Guake Properties.
> Add F12 as 'Custom Shortcut' to command 'guake-toggle' in Gnome, Settings, Keyboard, View and Customize Shortcuts.

Worked for me, thanks!

**Comment by Davidy22** [comment]
I'll get 47 when it comes to fedora 41, but for the time being does @johnheenan's workaround work for you?

Labelled as a workaround but given that it's necessary on wayland because of policy I do have a mind to just make it the default with instructions on how to do it in the settings
