### ISSUE TITLE
Starting Guake fails

### ISSUE THREAD

**Issue by Queuecumber** [Guake/guake#468]
Fresh install from latest git on ubuntu 14.04 gives the following error on start 

     % guake                                 
    /usr/lib/python2.7/dist-packages/guake/guake_app.py:1303: GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
     self.mainframe.pack_start(self.mainframe, expand=True, fill=True, padding=0)
    Traceback (most recent call last):
     File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/usr/lib/python2.7/dist-packages/guake/main.py", line 221, in <module>
        exec_main()
      File "/usr/lib/python2.7/dist-packages/guake/main.py", line 217, in exec_main
        if not main():
      File "/usr/lib/python2.7/dist-packages/guake/main.py", line 132, in main
        instance = Guake()
      File "/usr/lib/python2.7/dist-packages/guake/guake_app.py", line 268, in __init__
        self.add_tab()
      File "/usr/lib/python2.7/dist-packages/guake/guake_app.py", line 1152, in add_tab
        box = GuakeTerminalBox()
      File "/usr/lib/python2.7/dist-packages/guake/terminal.py", line 248, in __init__
        self.terminal = GuakeTerminal()
      File "/usr/lib/python2.7/dist-packages/guake/terminal.py", line 79, in __init__
        self.configure_terminal()
      File "/usr/lib/python2.7/dist-packages/guake/terminal.py", line 96, in configure_terminal
        self.set_word_chars(word_chars)
    TypeError: Vte.Terminal.set_word_chars() argument 1 must be string, not None

Any idea if this is a bug on your end or if I did something wrong?

**Comment by Queuecumber** [comment]
Update: I did a complete removal of anything guake related following these steps:

`make uninstall` 
`sudo updatedb`
`locate guake`

I found that a few files were still hanging around so I deleted them:

`sudo rm -rf /usr/local/lib/python2.7/dist-packages/guake/`
`sudo rm -rf /usr/local/share/pixmaps/guake`
`sudo rm -rf /usr/local/share/guake`

Then rebuild and reinstalled guake and now it's working. I'm still not sure if this is a bug or not but hopefully that helps

**Comment by pypingou** [comment]
It's bug that has been fixed in the latest version, so we should be fine now :)

Thanks for the report though!

**Comment by Stibbons** [comment]
Thanks indeed
