### ISSUE TITLE
bug report--cannot start guake

### ISSUE THREAD

**Issue by cosmozhang** [Guake/guake#477]
with ubuntu12.02
/usr/local/lib/python2.7/dist-packages/guake/guake_app.py:1317: GtkWarning: gtk_box_pack: assertion `child->parent == NULL' failed
  self.mainframe.pack_start(self.mainframe, expand=True, fill=True, padding=0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/guake/main.py", line 221, in <module>
    exec_main()
  File "/usr/local/lib/python2.7/dist-packages/guake/main.py", line 217, in exec_main
    if not main():
  File "/usr/local/lib/python2.7/dist-packages/guake/main.py", line 132, in main
    instance = Guake()
  File "/usr/local/lib/python2.7/dist-packages/guake/guake_app.py", line 268, in __init__
    self.add_tab()
  File "/usr/local/lib/python2.7/dist-packages/guake/guake_app.py", line 1166, in add_tab
    box = GuakeTerminalBox()
  File "/usr/local/lib/python2.7/dist-packages/guake/terminal.py", line 247, in __init__
    self.terminal = GuakeTerminal()
  File "/usr/local/lib/python2.7/dist-packages/guake/terminal.py", line 79, in __init__
    self.configure_terminal()
  File "/usr/local/lib/python2.7/dist-packages/guake/terminal.py", line 96, in configure_terminal
    self.set_word_chars(word_chars)
TypeError: Vte.Terminal.set_word_chars() argument 1 must be string, not None

**Comment by pypingou** [comment]
Have you tried the latest version? I'm fairly sure this has been fixed there.

**Comment by Stibbons** [comment]
look like an incompatibility with your version of python-vte
