### ISSUE TITLE
Guake crashes when changing preferences

### ISSUE THREAD

**Issue by kookerus** [Guake/guake#491]
When right clicking in Guake and selecting "preferences", or when running `guake-prefs`, Guake immediately crashes and outputs
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/guake/prefs.py", line 1045, in <module>
    setup_standalone_signals(PrefsDialog()).show()
  File "/usr/local/lib/python2.7/dist-packages/guake/prefs.py", line 502, in __init__
    self.load_configs()
  File "/usr/local/lib/python2.7/dist-packages/guake/prefs.py", line 827, in load_configs
    self.set_palette_colors(value)
  File "/usr/local/lib/python2.7/dist-packages/guake/prefs.py", line 625, in set_palette_colors
    color = gtk.gdk.color_parse(palette[i])
IndexError: list index out of range`

Guake itself runs fine, but no preferences can be changed, and that's a bit of an issue.

**Comment by Stibbons** [comment]
ok I look at this right now

**Comment by Stibbons** [comment]
Should be fixed by 67be47b ! Sorry for this issue!

**Comment by kookerus** [comment]
I feel really stupid, but I'm new to git, and I've looked everywhere, and I can't figure out how to checkout that single commit.

**Comment by kookerus** [comment]
Thanks, this definitely fixed it!

**Comment by Stibbons** [comment]
thanks for the report :)
