### ISSUE TITLE
cannot open preference window and the color palette is broken

### ISSUE THREAD

**Issue by georeth** [Guake/guake#494]
After upgrade to the lastest commit a1dcbc2a647e6bc4b9536d75306bf60bbff7425d, I can't open preference window and the color palette is broken.
Then, I checkout the commit 7fdec8dfa4a70186c66cd527450325d5717e8917, and that version works.
I think the feature "allow font and background color from palette" may have some problem.

Under Ubuntu 14.04LTS amd64

below is the error message of the following command
```bash
$ guake -p
```

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/guake/main.py", line 222, in <module>
    exec_main()
  File "/usr/local/lib/python2.7/dist-packages/guake/main.py", line 218, in exec_main
    if not main():
  File "/usr/local/lib/python2.7/dist-packages/guake/main.py", line 149, in main
    remote_object.show_prefs()
  File "/usr/local/lib/python2.7/dist-packages/guake/dbusiface.py", line 113, in show_prefs
    self.guake.show_prefs()
  File "/usr/local/lib/python2.7/dist-packages/guake/guake_app.py", line 478, in show_prefs
    PrefsDialog().show()
  File "/usr/local/lib/python2.7/dist-packages/guake/prefs.py", line 502, in __init__
    self.load_configs()
  File "/usr/local/lib/python2.7/dist-packages/guake/prefs.py", line 827, in load_configs
    self.set_palette_colors(value)
  File "/usr/local/lib/python2.7/dist-packages/guake/prefs.py", line 625, in set_palette_colors
    color = gtk.gdk.color_parse(palette[i])
IndexError: list index out of range
```

**Comment by georeth** [comment]
it seems to have been fixed in #491

but I can't get that commit 67be47b408d15d433d85044dca7d21f1cbfdae0a through git pull.

I am not familiar with git.

**Comment by kookerus** [comment]
Did you add Stibbons' repo? You can either clone the repo in a new directory, or add it through `git remote add`

**Comment by Stibbons** [comment]
Seems like I forgot to merge my fork. Done in https://github.com/Guake/guake/pull/496
