### ISSUE TITLE
Guake Preferences crashing again

### ISSUE THREAD

**Issue by kookerus** [Guake/guake#495]
Output:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/guake/prefs.py", line 1045, in <module>
    setup_standalone_signals(PrefsDialog()).show()
  File "/usr/local/lib/python2.7/dist-packages/guake/prefs.py", line 502, in __init__
    self.load_configs()
  File "/usr/local/lib/python2.7/dist-packages/guake/prefs.py", line 806, in load_configs
    self.get_widget('font_style').set_font_name(value)
TypeError: Gtk.FontButton.set_font_name() argument 1 must be string, not None`

I originally had this issue that was fixed by 67be47b, but this is a different issue.

**Comment by pypingou** [comment]
Are you using the latest version of guake?

**Comment by kookerus** [comment]
I am

**Comment by Stibbons** [comment]
Look like a regression from my latest dev. Weird I didn't had any issue. I'll check it tomorrow

**Comment by Stibbons** [comment]
Should be fixed by 07267a26b3a7992b5ad07faee0c872c9e8b5914e

**Comment by kookerus** [comment]
Confirmed fixed. Thank you very much!
