### ISSUE TITLE
NoneType object has no attribute 'unstick'

### ISSUE THREAD

**Issue by hackel** [Guake/guake#511]
This bug report may not be relevant, since it's from Guake 0.5.2.  I was working in Guake, ran a java application from an open tab, and now suddenly I can't bring the guake terminal back up.  When I try to run guake from another xterm window, I get the error below.  In the end, I just had to kill Guake manually, and now after restarting it, it seems to be working again.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/guake/main.py", line 216, in <module>
    exec_main()
  File "/usr/lib/python2.7/dist-packages/guake/main.py", line 212, in exec_main
    if not main():
  File "/usr/lib/python2.7/dist-packages/guake/main.py", line 183, in main
    remote_object.show_about()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/dist-packages/guake/dbusiface.py", line 104, in show_about
    self.guake.show_about()
  File "/usr/lib/python2.7/dist-packages/guake/guake_app.py", line 453, in show_about
    self.hide()
  File "/usr/lib/python2.7/dist-packages/guake/guake_app.py", line 592, in hide
    self.get_widget('window-root').unstick()
AttributeError: 'NoneType' object has no attribute 'unstick'
```

**Comment by aichingm** [comment]
This seams to be triggered by a dbus call to show_about, which now works just fine.

    guake --about

Can not be reproduced with current HEAD -> closing.
