### ISSUE TITLE
Terminal widget disappears at random times

### ISSUE THREAD

**Issue by fstirlitz** [Guake/guake#592]
Sometimes when I run Guake (0.7.2) for a considerable amount of time, I switch to an inactive tab and notice that the terminal emulator widget is no longer there, as if ripped out of the window (the scrollbar is left intact, and moves to the left), leaving me with no other option than to forcibly close the tab. It sometimes happens to several tabs at once; I cannot recall it happening to an active tab.

I am unable to determine what exactly causes this.

**Comment by fstirlitz** [comment]
Here's how it looks like:
![guake](https://cloud.githubusercontent.com/assets/4331184/9055745/d5e45aaa-3a8d-11e5-8542-d56b313dddfe.png)

**Comment by fstirlitz** [comment]
After experiencing this bug again recently, I forcibly closed every tab in which the terminal widget disappeared, and found out that I can only open new tabs if the current tab is the first.

After I looked into `~/.xsession-errors` I found that the following is added every time I try to open a new tab:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/guake/guake_app.py", line 1012, in accel_add
    self.add_tab()
  File "/usr/lib/python2.7/site-packages/guake/guake_app.py", line 1393, in add_tab
    final_params = self.get_fork_params(default_params)
  File "/usr/lib/python2.7/site-packages/guake/guake_app.py", line 1314, in get_fork_params
    params['directory'] = self.get_current_dir()
  File "/usr/lib/python2.7/site-packages/guake/guake_app.py", line 1289, in get_current_dir
    cwd = os.readlink("/proc/%d/cwd" % active_terminal.get_pid())
TypeError: %d format: a number is required, not NoneType
```

I also found the following messages before this: 
```
/usr/lib/python2.7/site-packages/guake/guake_app.py:1614: GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
  self.mainframe.pack_start(self.mainframe, expand=True, fill=True, padding=0)
```
```
/usr/lib/python2.7/site-packages/guake/guake_app.py:711: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
  self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_DOCK)
/usr/lib/python2.7/site-packages/guake/guake_app.py:712: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
  self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_NORMAL)
```
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/guake/guake_app.py", line 1012, in accel_add
    self.add_tab()
  File "/usr/lib/python2.7/site-packages/guake/guake_app.py", line 1393, in add_tab
    final_params = self.get_fork_params(default_params)
  File "/usr/lib/python2.7/site-packages/guake/guake_app.py", line 1314, in get_fork_params
    params['directory'] = self.get_current_dir()
  File "/usr/lib/python2.7/site-packages/guake/guake_app.py", line 1289, in get_current_dir
    cwd = os.readlink("/proc/%d/cwd" % active_terminal.get_pid())
OSError: [Errno 2] Aucun fichier ou dossier de ce type: '/proc/31286/cwd'
```
(this one was repeated 9 times)
