### ISSUE TITLE
XDG_CURRENT_DESKTOP not set

### ISSUE THREAD

**Issue by creakings** [Guake/guake#594]
I am running Ubuntu without using or installing any 'Unity'. Instead i run a window-manager called Fluxbox.
The problem is that the environment variable XDG_CURRENT_DESKTOP seems not to be set.

I don´t know if that is an issue on other systems. 
However, maybe you could first check if any environment variable exists.
For example in my environment only XDG_DESKTOP_SESSION is set to 'Fluxbox'. 

Python Stack Trace
```
/usr/lib/python2.7/dist-packages/guake/guake_app.py:1625: GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
  self.mainframe.pack_start(self.mainframe, expand=True, fill=True, padding=0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/guake/gconfhandler.py", line 146, in size_changed
    self.guake.set_final_window_rect()
  File "/usr/lib/python2.7/dist-packages/guake/guake_app.py", line 833, in set_final_window_rect
    if self.is_using_unity():
  File "/usr/lib/python2.7/dist-packages/guake/guake_app.py", line 801, in is_using_unity
    if os.environ.get('XDG_CURRENT_DESKTOP').lower() == "unity".lower():
AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/guake/gconfhandler.py", line 146, in size_changed
    self.guake.set_final_window_rect()
  File "/usr/lib/python2.7/dist-packages/guake/guake_app.py", line 833, in set_final_window_rect
    if self.is_using_unity():
  File "/usr/lib/python2.7/dist-packages/guake/guake_app.py", line 801, in is_using_unity
    if os.environ.get('XDG_CURRENT_DESKTOP').lower() == "unity".lower():
AttributeError: 'NoneType' object has no attribute 'lower'
```

Suggestion for a fix:
```
797,800c797,799
<             if os.environ.get('XDG_DESKTOP_SESSION'):
<                 if os.environ.get('DESKTOP_SESSION').lower() == "gnome".lower():
<                     log.debug("Unity detected")
<                     return True
---
>             if os.environ.get('DESKTOP_SESSION').lower() == "gnome".lower():
>                 log.debug("Unity detected")
>                 return True
802,805c801,803
<             if os.environ.get('XDG_CURRENT_DESKTOP'):
<                 if os.environ.get('XDG_CURRENT_DESKTOP').lower() == "unity".lower():
<                     log.debug("Unity detected")
<                     return True
---
>             if os.environ.get('XDG_CURRENT_DESKTOP').lower() == "unity".lower():
>                 log.debug("Unity detected")
>                 return True
```

**Comment by pypingou** [comment]
Even simpler:
````
if os.environ.get('XDG_CURRENT_DESKTOP', '').lower()
````
In this case if ``XDG_CURRENT_DESKTOP`` is undefined, it will default to ``''`` instead of returning ``None``

**Comment by Stibbons** [comment]
yes, it is already fixed on HEAD :)

**Comment by ZiTAL** [comment]
in $HOME/.bashrc add

export XDG_CURRENT_DESKTOP="fluxbox"
