### ISSUE TITLE
Using --rename-tab results in AttributeError

### ISSUE THREAD

**Issue by bergfried** [Guake/guake#868]
Running `guake --rename-tab=asdf` results in

````
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/guake/main.py", line 253, in <module>
    exec_main()
  File "/usr/lib/python2.7/site-packages/guake/main.py", line 249, in exec_main
    if not main():
  File "/usr/lib/python2.7/site-packages/guake/main.py", line 201, in main
    remote_object.rename_tab(int(options.tab_index), options.rename_tab)
  File "/usr/lib/python2.7/site-packages/guake/dbusiface.py", line 109, in rename_tab
    self.guake.rename_tab(tab_index, new_text)
  File "/usr/lib/python2.7/site-packages/guake/guake_app.py", line 1574, in rename_tab
    setattr(self.selected_tab, 'custom_label_text', new_text)
AttributeError: 'NoneType' object has no attribute 'custom_label_text'
````

Using Guake 0.8.8.

**Comment by Davidy22** [comment]
Does not throw an attribute error, but also doesn't work still.

**Comment by Davidy22** [comment]
--rename-tab now works, and you can use --tab-index to target a numbered tab
