### ISSUE TITLE
Guake fails to load with error "ImportError: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates"

### ISSUE THREAD

**Issue by isaacsando** [Guake/guake#889]
### Environment details
Guake version: 0.8.8-1
Arch Linux: kernel 4.8.16.r201701062021-1-grsec
Gnome: 3.22.2 (using X instead of Wayland)

### Issue
When I try to launch guake from the terminal I get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/guake/main.py", line 28, in <module>
    import gtk
  File "/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 40, in <module>
    from gtk import _gtk
ImportError: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
```

Please let me know what other information I can provide to help track down the issue.

Thanks!

**Comment by gogoplata** [comment]
Just wanted to add that I have the same problem and the error message is identical.

I'm running the following : 

Guake version: 0.8.8-1
Kernel: x86_64 Linux 4.8.13-1-ARCH
DE: XFCE4 v4.12

**Comment by isaacsando** [comment]
I see that GTK was upgraded yesterday from 3.22.5-1 to 3.22.6-1 and harfbuzz from 1.3.4-1 to 1.4.1-1. I haven't had time to downgrade and test, but that may be where the issue came in. I just started getting this error this morning.

**Comment by khaledhosny** [comment]
See https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671

**Comment by isaacsando** [comment]
Thank you for the link @khaledhosny. I do indeed have the infinality packages installed so I'm guessing this will solve the issue. Looks like a few steps to try it out so I'll have to try it out a bit later.

**Comment by gogoplata** [comment]
Thanks @khaledhosny. Can confirm that this resolved the issue.

**Comment by isaacsando** [comment]
This fixed it for me, too. Thank you @khaledhosny!!!
