### ISSUE TITLE
guake fedora 25

### ISSUE THREAD

**Issue by brumle80** [Guake/guake#916]
seems some update borked guake on Fedora 25
fully updated as of today
any workarounds for this?

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/guake/main.py", line 27, in <module>
    import dbus
  File "/usr/lib64/python2.7/site-packages/dbus/__init__.py", line 77, in <module>
    import dbus.types as types
  File "/usr/lib64/python2.7/site-packages/dbus/types.py", line 6, in <module>
    from _dbus_bindings import (
ImportError: ./_dbus_bindings.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8
```

**Comment by brumle80** [comment]
seems today's dnf update update fixed whatever was broken :)
