### ISSUE TITLE
guake won't start due to pynotify AttributeError

### ISSUE THREAD

**Issue by mraduldubey** [Guake/guake#925]
This error pops up while trying to run guake on Ubuntu:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/guake/main.py", line 43, in <module>
    from guake.guake_app import Guake
  File "/usr/lib/python2.7/dist-packages/guake/guake_app.py", line 49, in <module>
    import guake.notifier
  File "/usr/lib/python2.7/dist-packages/guake/notifier.py", line 31, in <module>
    pynotify.init("Guake")
AttributeError: 'module' object has no attribute 'init'

**Comment by mraduldubey** [comment]
Not a bug in guake. It was due to a conflict of pynotify with one instance installed by apt while other by pip. Check this: https://stackoverflow.com/questions/43263336/guake-terminal-throws-pynotify-attribute-error/43461530#43461530
