### ISSUE TITLE
Guake won't start (Python problem?)

### ISSUE THREAD

**Issue by VasuLief** [Guake/guake#927]
Guake won't start after working for a few months.. Any Ideas?

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/guake/main.py", line 27, in <module>
    import dbus
  File "/usr/lib/python2.7/dist-packages/dbus/__init__.py", line 103, in <module>
    from dbus._dbus import Bus, SystemBus, SessionBus, StarterBus
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 39, in <module>
    from dbus.bus import BusConnection
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 39, in <module>
    from dbus.connection import Connection
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 37, in <module>
    from dbus.proxies import ProxyObject
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 34, in <module>
    from dbus._expat_introspect_parser import process_introspection_data
  File "/usr/lib/python2.7/dist-packages/dbus/_expat_introspect_parser.py", line 26, in <module>
    from xml.parsers.expat import ParserCreate
ImportError: ./xml.so: undefined symbol: convert_to_long

**Comment by VasuLief** [comment]
$ python --version
Python 2.7.12

**Comment by Stibbons** [comment]
which system are you?

**Comment by VasuLief** [comment]
I'm on Ubuntu 16.04.1 with Gnome

**Comment by VasuLief** [comment]
Little Update:

When I try to start guake from the app launcher or from the regular terminal, it fails. But when I start it from the Drop Down Terminal (https://extensions.gnome.org/extension/442/drop-down-terminal/) it works!
