### ISSUE TITLE
Guake Preferences doesn't open

### ISSUE THREAD

**Issue by jam1e** [Guake/guake#971]
When right-clicking then choosing Preferences from the menu, no window appears. When running the command `guake-prefs` I get the following error:

`(prefs.py:24712): libglade-WARNING **: unknown attribute `swapped' for <signal>.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/guake/prefs.py", line 1207, in <module>
    setup_standalone_signals(PrefsDialog()).show()
  File "/usr/local/lib/python2.7/dist-packages/guake/prefs.py", line 515, in __init__
    self.load_configs()
  File "/usr/local/lib/python2.7/dist-packages/guake/prefs.py", line 894, in load_configs
    self.get_widget('startup_script').set_text(value)
TypeError: Gtk.Entry.set_text() argument 1 must be string, not None
`

**Comment by Stibbons** [comment]
Should be closed by 5e7c7cf.
